import { mkdtemp, mkdir, writeFile, readFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { createHash } from "node:crypto";
import { describe, it, expect } from "vitest";
import { activationRoot, validateActiveCorpus, activateCorpus, rollbackCorpus } from "./corpusActivation";
const hash=(s:string)=>createHash("sha256").update(s).digest("hex");
async function version(root:string,version:string,count:number){const d=path.join(root,"versions",version);await mkdir(d,{recursive:true});const body=JSON.stringify({records:Array.from({length:count},(_,i)=>({id:`${version}-${i}`}))});await writeFile(path.join(d,"canonical.json"),body);const manifest={schemaVersion:1 as const,corpusVersion:version,canonicalCount:count,files:{"canonical.json":{path:"canonical.json",sha256:hash(body),count}}};await writeFile(path.join(d,"manifest.json"),JSON.stringify(manifest));return manifest;}
describe("corpus activation",()=>{it("validates, activates atomically, and rolls back",async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),"rama-"));const v14=await version(dir,"v1.4.0",550);await version(dir,"v1.5.0",1092);const r=activationRoot(dir);await writeFile(r.activePointerPath,JSON.stringify({schemaVersion:1,activeCorpusVersion:"v1.4.0",canonicalCount:550,manifestHash:hash(JSON.stringify(v14)),activatedAt:new Date().toISOString(),previousCorpusVersion:null,activationId:"boot"}));expect((await validateActiveCorpus(r)).pointer.canonicalCount).toBe(550);await activateCorpus(r,"v1.5.0");expect((await validateActiveCorpus(r)).pointer.activeCorpusVersion).toBe("v1.5.0");await rollbackCorpus(r);expect((await validateActiveCorpus(r)).pointer.activeCorpusVersion).toBe("v1.4.0");});it("fails closed when a version file is corrupted",async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),"rama-"));const v14=await version(dir,"v1.4.0",550);const r=activationRoot(dir);await writeFile(r.activePointerPath,JSON.stringify({schemaVersion:1,activeCorpusVersion:"v1.4.0",canonicalCount:550,manifestHash:hash(JSON.stringify(v14)),activatedAt:new Date().toISOString(),previousCorpusVersion:null,activationId:"boot"}));await writeFile(path.join(dir,"versions","v1.4.0","canonical.json"),"corrupt");await expect(validateActiveCorpus(r)).rejects.toThrow("Hash mismatch");});});
