import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

const root = "/home/ubuntu/ramaverse";
const read = (relative) => JSON.parse(fs.readFileSync(path.join(root, relative), "utf8"));
const write = (relative, value) => fs.writeFileSync(path.join(root, relative), JSON.stringify(value, null, 2) + "\n");
const hash = (relative) => crypto.createHash("sha256").update(fs.readFileSync(path.join(root, relative))).digest("hex");
const payloadNames = fs.readdirSync(path.join(root, "data/staging/post_v1")).filter((name) => /^AYODHYA_S\d+_SOURCE_BACKED_RECORDS\.json$/.test(name)).sort((a, b) => Number(a.match(/S(\d+)/)[1]) - Number(b.match(/S(\d+)/)[1]));
const payloads = [{ path: "data/staging/physical/STAGING_RECORDS.json", records: read("data/staging/physical/STAGING_RECORDS.json") }, ...payloadNames.map((name) => ({ path: `data/staging/post_v1/${name}`, records: read(`data/staging/post_v1/${name}`).records ?? [] }))];
const records = payloads.flatMap((payload) => payload.records.map((record) => ({ ...record, _payload: payload.path })));
const ids = records.map((record) => record.candidate_id).filter(Boolean);
const duplicateIds = [...new Set(ids.filter((id, index) => ids.indexOf(id) !== index))].sort();
const s30 = read("data/staging/post_v1/AYODHYA_S30_SOURCE_BACKED_RECORDS.json");
const s31 = read("data/staging/post_v1/AYODHYA_S31_SOURCE_BACKED_RECORDS.json");
if (s30.records.length !== s30.recordCount || s31.records.length !== s31.recordCount || duplicateIds.length > 0) throw new Error("New sequential payload count or duplicate gate failed");

const priorSourceLedger = read("SOURCE_LEDGER_V10.json");
const newSources = [
  { source_id: "src-valmiki-ayodhya-s30-stotranidhi", title: "Valmiki Ramayana — Ayodhya Kanda — Sarga 30", repository: "Stotra Nidhi", edition_or_recension: "Traditional digital IAST text presentation", language: "Sanskrit (IAST)", sourceType: "PRIMARY_TEXT_DIGITAL_RENDITION", kanda: "Ayodhya Kanda", sarga: 30, verse_range: "2.30.1–2.30.47", url: "https://stotranidhi.com/en/ayodhya-kanda-sarga-30-in-english/", accessedAt: "2026-08-19", rights_status: "External reference; only original structured paraphrases are stored in staging.", tradition: "Valmiki", confidence: "high", caveat: "Primary digital acquisition locator for this batch; historical duty and dramatic distress language are contextual only." },
  { source_id: "src-valmiki-ayodhya-s30-vedapath-v1-crosscheck", title: "Valmiki Ramayana 2.30.1 — verse-level cross-check", repository: "Vedapath", edition_or_recension: "Digital verse presentation", language: "Sanskrit with English interface", sourceType: "PRIMARY_TEXT_DIGITAL_CROSSCHECK", kanda: "Ayodhya Kanda", sarga: 30, verse_range: "2.30.1", url: "https://vedapath.app/en/ramayana/ayodhya-kanda/30/1", accessedAt: "2026-08-19", rights_status: "External reference; no continuous source text is reproduced in staging.", tradition: "Valmiki", confidence: "medium", caveat: "Used only to corroborate chapter opening and protagonist identification." },
  { source_id: "src-valmiki-ayodhya-s30-vedapath-v21-crosscheck", title: "Valmiki Ramayana 2.30.21 — distress-context cross-check", repository: "Vedapath", edition_or_recension: "Digital verse presentation", language: "Sanskrit with English interface", sourceType: "PRIMARY_TEXT_DIGITAL_CROSSCHECK", kanda: "Ayodhya Kanda", sarga: 30, verse_range: "2.30.21", url: "https://vedapath.app/en/ramayana/ayodhya-kanda/30/21", accessedAt: "2026-08-19", rights_status: "External reference; no continuous source text is reproduced in staging.", tradition: "Valmiki", confidence: "medium", caveat: "Used only to corroborate the verse locator and non-instructional distress safeguard." },
  { source_id: "src-valmiki-ayodhya-s31-sanskritdocuments", title: "Valmiki Ramayana — Ayodhya Kanda — Sarga 31", repository: "SanskritDocuments.org", edition_or_recension: "Traditional digital Sanskrit recension with English word-for-word translation", language: "Sanskrit with English translation", sourceType: "PRIMARY_TEXT_DIGITAL_RENDITION", kanda: "Ayodhya Kanda", sarga: 31, verse_range: "2.31.1–2.31.35", url: "https://sanskritdocuments.org/sites/valmikiramayan/ayodhya/sarga31/ayodhyaroman31.htm", accessedAt: "2026-08-19", rights_status: "External digital text; only original structured paraphrases are stored in staging.", tradition: "Valmiki", confidence: "high", caveat: "Primary acquisition locator. A two-verse difference against the Stotra Nidhi presentation is explicitly recorded as edition variance." },
  { source_id: "src-valmiki-ayodhya-s31-stotranidhi-crosscheck", title: "Ayodhya Kanda Sarga 31 — IAST text cross-check", repository: "Stotra Nidhi", edition_or_recension: "Traditional digital IAST text presentation", language: "Sanskrit (IAST)", sourceType: "PRIMARY_TEXT_DIGITAL_CROSSCHECK", kanda: "Ayodhya Kanda", sarga: 31, verse_range: "Stotra Nidhi 1–37; two marked additional verses after verse 19", url: "https://stotranidhi.com/en/ayodhya-kanda-sarga-31-in-english/", accessedAt: "2026-08-19", rights_status: "External reference; no continuous source text is reproduced in staging.", tradition: "Valmiki", confidence: "medium", caveat: "Used to corroborate chapter identity and document an edition variance, not to silently expand the primary-record locator." },
  { source_id: "src-valmiki-ayodhya-s31-vedapath-v2-crosscheck", title: "Valmiki Ramayana 2.31.1–2 — opening cross-check", repository: "Vedapath", edition_or_recension: "Digital verse presentation", language: "Sanskrit with English interface", sourceType: "PRIMARY_TEXT_DIGITAL_CROSSCHECK", kanda: "Ayodhya Kanda", sarga: 31, verse_range: "2.31.1–2.31.2", url: "https://vedapath.app/en/ramayana/ayodhya-kanda/31/2", accessedAt: "2026-08-19", rights_status: "External reference; no continuous source text is reproduced in staging.", tradition: "Valmiki", confidence: "medium", caveat: "Used only to corroborate opening narrative context and Lakshmana's entrance." }
];
const knownSourceIds = new Set(priorSourceLedger.sources.map((source) => source.source_id));
const sourceLedger = { ...priorSourceLedger, ledgerId: "ramaverse-master-source-ledger-vnext", generatedAt: "2026-08-19T14:42:00.000Z", sources: [...priorSourceLedger.sources, ...newSources.filter((source) => !knownSourceIds.has(source.source_id))] };
write("SOURCE_LEDGER_VNEXT.json", sourceLedger);

const ledger = {
  ledgerId: "ramaverse-website-staging-master-vnext",
  generatedAt: "2026-08-19T14:42:00.000Z",
  mode: "physical-records-only",
  historicalCanonicalBaseline: 550,
  stagingPublished: 0,
  physicallyAvailableUniqueRecords: records.length,
  candidateRecordsNotCountedAsPhysicalStaging: 7,
  recordPayloads: payloads.map((payload) => ({ path: payload.path, records: payload.records.length })),
  duplicates: { candidateIds: duplicateIds, count: duplicateIds.length },
  latestVerifiedCoverage: { kanda: "Ayodhya Kanda", sarga: 31, verseRange: "2.31.1–2.31.35", status: "PHYSICAL_STAGING_SOURCE_BACKED", editionVariance: "Stotra Nidhi includes two marked additional verses after primary-locator verse 19." },
  nextAcquisitionPoint: { kanda: "Ayodhya Kanda", sarga: 32, verseRange: "2.32.1 onward", status: "SOURCE_PROCUREMENT_PENDING" },
  publicSurfacePolicy: { search: "CANONICAL_ONLY", ask: "CANONICAL_ONLY", stagingExposure: 0 }
};
write("RAMAVERSE_STAGING_MASTER_LEDGER_VNEXT.json", ledger);
write("EXACT_PHYSICAL_CONTINUATION_VNEXT.json", { ledgerId: "ramaverse-exact-physical-continuation-vnext", generatedAt: "2026-08-19T14:42:00.000Z", historicalCanonicalBaseline: 550, physicalStagingCount: records.length, last_fully_acquired_kanda: "Ayodhya Kanda", last_fully_acquired_sarga: 31, last_fully_acquired_verse: "2.31.35", next_unacquired_verse: "2.32.1", source_id: "src-valmiki-ayodhya-s31-sanskritdocuments", source_locator: "SanskritDocuments, Valmiki Ramayana, Ayodhya Kanda, Sarga 31, verses 2.31.1–2.31.35", edition_variance: "Stotra Nidhi presents two marked additional verses after verse 19; no variant content is silently merged.", supporting_record_ids: ["stg-postv1-ayodhyakanda-s31-sarga-001", "stg-postv1-ayodhyakanda-s31-source-001"], duplicate_prevention: "New acquisition begins at Sarga 32, verse 2.32.1 and retains all variants in separate review state." });
write("S30_SOURCE_SCOPE_EVIDENCE.json", { evidenceId: "ramaverse-s30-source-scope-v1", generatedAt: "2026-08-19T14:42:00.000Z", primarySource: { sourceId: "src-valmiki-ayodhya-s30-stotranidhi", url: "https://stotranidhi.com/en/ayodhya-kanda-sarga-30-in-english/", verseRange: "2.30.1–2.30.47", verifiedVerseEnd: "2.30.47", accessStatus: "EXTRACTED" }, crossChecks: [{ sourceId: "src-valmiki-ayodhya-s30-vedapath-v1-crosscheck", confirmedVerse: "2.30.1" }, { sourceId: "src-valmiki-ayodhya-s30-vedapath-v21-crosscheck", confirmedVerse: "2.30.21" }], safetyReview: { dramaticExpressionVerses: ["2.30.19–2.30.21"], historicalDutyVerses: ["2.30.30–2.30.37"], labels: ["NARRATIVE_DRAMATIC_EXPRESSION", "NOT_INSTRUCTIONAL", "HISTORICAL_LITERARY_CONTEXT", "NO_OUTCOME_GUARANTEE"] }, result: "PASS" });
write("S31_SOURCE_SCOPE_EVIDENCE.json", { evidenceId: "ramaverse-s31-source-scope-v1", generatedAt: "2026-08-19T14:42:00.000Z", primarySource: { sourceId: "src-valmiki-ayodhya-s31-sanskritdocuments", url: "https://sanskritdocuments.org/sites/valmikiramayan/ayodhya/sarga31/ayodhyaroman31.htm", verseRange: "2.31.1–2.31.35", verifiedVerseEnd: "2.31.35", accessStatus: "EXTRACTED" }, crossChecks: [{ sourceId: "src-valmiki-ayodhya-s31-stotranidhi-crosscheck", confirmedChapterScope: "1–37 with two marked additions after verse 19" }, { sourceId: "src-valmiki-ayodhya-s31-vedapath-v2-crosscheck", confirmedVerseRange: "2.31.1–2" }], knownEditionVariance: { primaryVerseCount: 35, crosscheckVerseCount: 37, handling: "Variant is logged for review; only the primary 35-verse locator underlies batch records." }, result: "PASS" });

const reviewState = (record) => String(record.tamil_review_status ?? record.review_status ?? "NEEDS_HUMAN_REVIEW").toUpperCase().replace("NEEDS_HUMAN_TAMIL_REVIEW", "NEEDS_HUMAN_REVIEW").replace("NEEDS_TAMIL_REVIEW", "NEEDS_HUMAN_REVIEW");
const priorityFor = (record) => ({ DIALOGUE: "P1", HISTORICAL_TEXTUAL_NORM: "P2", THEME: "P2", EVENT: "P2", SARGA: "P2", RELATIONSHIP: "P3", CHARACTER_REFERENCE: "P3", JOURNEY: "P3", OBJECT_REFERENCE: "P3", VERSE_SECTION: "P3", SOURCE_REFERENCE: "P4" }[record.record_type] ?? "P4");
const reviewRecords = records.map((record) => ({ record_id: record.candidate_id, record_type: record.record_type, source_locator: record.source_locator ?? record.canonical_source_locator ?? null, current_tamil_text: record.tamil_draft ?? record.tamil_explanation ?? null, translation_status: reviewState(record), priority: priorityFor(record), review_reason: priorityFor(record) === "P1" ? "Dialogue needs human editorial review before any reconciliation consideration." : record.record_type === "HISTORICAL_TEXTUAL_NORM" ? "Historical-context safeguard and Tamil wording need human editorial review." : "Tamil editorial review required before reconciliation; current record remains unpublished.", merge_state: record.merge_state ?? "awaiting_v1_4_0_reconciliation", publication_state: "STAGING_QUARANTINE_ONLY" })).sort((a, b) => a.priority.localeCompare(b.priority) || a.record_id.localeCompare(b.record_id));
write("TAMIL_EDITORIAL_REVIEW_QUEUE_VNEXT.json", { queueId: "ramaverse-tamil-editorial-review-queue-vnext", generatedAt: "2026-08-19T14:42:00.000Z", scope: "All physical staging records; none are production approved or public.", countsByTranslationState: reviewRecords.reduce((counts, record) => ({ ...counts, [record.translation_status]: (counts[record.translation_status] ?? 0) + 1 }), {}), countsByPriority: reviewRecords.reduce((counts, record) => ({ ...counts, [record.priority]: (counts[record.priority] ?? 0) + 1 }), {}), records: reviewRecords });

const candidates = read("POST_V1_RECONCILIATION_CANDIDATES.json").candidates ?? [];
const typeCounts = records.reduce((counts, record) => ({ ...counts, [record.record_type]: (counts[record.record_type] ?? 0) + 1 }), {});
write("V1_5_RECONCILIATION_PREVIEW.json", { previewId: "ramaverse-v1.5-reconciliation-preview-vnext", generatedAt: "2026-08-19T14:42:00.000Z", status: "EDITORIAL_PREVIEW_ONLY_NOT_PRODUCTION_READY", historicalCanonicalBaseline: 550, stagingPublished: 0, physicalStagingRecords: records.length, counts: { NEW_CANONICAL_CANDIDATE: records.length, ENRICH_EXISTING: 0, DUPLICATE: duplicateIds.length, VARIANT: 1, CONFLICT: 0, SOURCE_REVIEW: records.length, TAMIL_REVIEW: reviewRecords.filter((record) => record.translation_status !== "HUMAN_REVIEWED").length, REJECTED: 0 }, pendingHistoricalCandidates: candidates.length, guardrails: ["No staging record is added to the historical canonical baseline.", "No staging record is sent to public Search, public Ask, public graph, or the frozen v1.4.0 pack.", "Edition variants remain distinct until formal editorial reconciliation." ] });
write("RAMAVERSE-CANONICAL-MOBILE-PACK-v1.5.0-CANDIDATE-METADATA.json", { metadataId: "ramaverse-v1.5.0-candidate-metadata-v1", generatedAt: "2026-08-19T14:42:00.000Z", status: "METADATA_ONLY_NOT_A_MOBILE_PACK", approvedMobilePack: "RAMAVERSE-CANONICAL-MOBILE-PACK-v1.4.0-FINAL-v2.zip", approvedPackModified: false, stagingRecordCount: records.length, candidateRecordIds: records.map((record) => record.candidate_id), eligibility: "Requires authoritative v1.5 reconciliation and Tamil editorial approval before any production pack may be produced.", stagingPublished: 0, publicExposure: 0 });

const relationEdges = records.filter((record) => record.record_type === "RELATIONSHIP" && record.subject && record.object).map((record) => ({ from: record.subject, to: record.object, relation: record.relation, evidence_id: record.candidate_id, source_id: record.source_id, verse_locator: record.verse_locator }));
const dialogueEdges = records.filter((record) => record.record_type === "DIALOGUE").map((record) => ({ from: record.speaker, to: record.listener, relation: "SPEAKS_TO", evidence_id: record.candidate_id, source_id: record.source_id, verse_locator: record.verse_locator }));
write("POST_V1_STAGING_KNOWLEDGE_GRAPH_VNEXT.json", { graphId: "ramaverse-post-v1-staging-knowledge-graph-vnext", generatedAt: "2026-08-19T14:42:00.000Z", visibility: "EDITORIAL_ONLY_STAGING", publicGraphExposure: 0, nodes: records.map((record) => ({ id: record.candidate_id, type: record.record_type, source_id: record.source_id ?? null, staging_state: "QUARANTINED" })), edges: [...relationEdges, ...dialogueEdges], safeguards: "Editorial evidence only. Public knowledge graph remains canonical-only." });
write("POST_V1_EDITORIAL_INDEX_VNEXT.json", { indexId: "ramaverse-post-v1-editorial-index-vnext", generatedAt: "2026-08-19T14:42:00.000Z", visibility: "EDITORIAL_ONLY_STAGING", canonicalBaseline: 550, stagingRecords: records.length, publicSearchEntries: 0, publicAskEntries: 0, byRecordType: typeCounts, bySarga: records.reduce((counts, record) => ({ ...counts, [`${record.kanda} ${record.sarga ?? "legacy"}`]: (counts[`${record.kanda} ${record.sarga ?? "legacy"}`] ?? 0) + 1 }), {}) });
write("RELATIONAL_DIALOGUE_EVIDENCE_VNEXT.json", { evidenceId: "ramaverse-relational-dialogue-evidence-vnext", generatedAt: "2026-08-19T14:42:00.000Z", visibility: "EDITORIAL_ONLY_STAGING", s30: { dialogues: s30.records.filter((record) => record.record_type === "DIALOGUE").map((record) => record.candidate_id), relationships: s30.records.filter((record) => record.record_type === "RELATIONSHIP").map((record) => record.candidate_id) }, s31: { dialogues: s31.records.filter((record) => record.record_type === "DIALOGUE").map((record) => record.candidate_id), relationships: s31.records.filter((record) => record.record_type === "RELATIONSHIP").map((record) => record.candidate_id) }, boundary: "All dialogue and relationship records are source-bound narrative evidence, not public advice or canonical claims." });

const state = read("RAMAVERSE_PROJECT_STATE.json");
write("RAMAVERSE_PROJECT_STATE.json", { ...state, RV_01_staging_count: records.length, staging_published: 0, staging_files: [...new Set([...state.staging_files, "data/staging/post_v1/AYODHYA_S30_SOURCE_BACKED_RECORDS.json", "data/staging/post_v1/AYODHYA_S31_SOURCE_BACKED_RECORDS.json"])], stable_id_registries: [...new Set([...state.stable_id_registries, "RAMAVERSE_STAGING_MASTER_LEDGER_VNEXT.json"])], RV_01_continuation: "Ayodhya Kanda Sarga 32, verse 2.32.1 onward", source_clusters: [...new Set([...state.source_clusters, "Valmiki Ramayana / Ayodhya Kanda / Sargas 30–31 physical source-backed staging"])], latest_batch_ids: ["AYODHYA_S30_SOURCE_BACKED_RECORDS", "AYODHYA_S31_SOURCE_BACKED_RECORDS", "POST_V1_EDITORIAL_INDEX_VNEXT", "POST_V1_STAGING_KNOWLEDGE_GRAPH_VNEXT"], task_output_map: { ...state.task_output_map, physical_ledger: "RAMAVERSE_STAGING_MASTER_LEDGER_VNEXT.json", continuation: "EXACT_PHYSICAL_CONTINUATION_VNEXT.json", source_ledger: "SOURCE_LEDGER_VNEXT.json", corpus_archive: "RAMAVERSE-CORPUS-AUTHORITY-POST-V1-vNEXT.zip" }, SHA256: { ...state.SHA256, s30_staging_payload: hash("data/staging/post_v1/AYODHYA_S30_SOURCE_BACKED_RECORDS.json"), s31_staging_payload: hash("data/staging/post_v1/AYODHYA_S31_SOURCE_BACKED_RECORDS.json"), staging_ledger_vnext: hash("RAMAVERSE_STAGING_MASTER_LEDGER_VNEXT.json") }, exact_next_point: "Ayodhya Kanda / Sarga 32 / verse 2.32.1", updated_at: "2026-08-19T14:42:00.000Z" });
console.log(JSON.stringify({ physicalStaging: records.length, s30Records: s30.records.length, s31Records: s31.records.length, sources: sourceLedger.sources.length, duplicateIds, status: "PASS" }, null, 2));
