import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { spawnSync } from "node:child_process";

const root = "/home/ubuntu/ramaverse", stage = "/tmp/ramaverse-v3-authority-archive", zip = "/home/ubuntu/RAMAVERSE-CORPUS-AUTHORITY-POST-V1-vNEXT.zip";
const rm = (target) => fs.rmSync(target, { recursive: true, force: true });
const mkdir = (target) => fs.mkdirSync(target, { recursive: true });
const cp = (relative, destination) => { const source = path.join(root, relative); if (!fs.existsSync(source)) throw new Error(`Missing archive input: ${relative}`); const output = path.join(stage, destination); mkdir(path.dirname(output)); fs.copyFileSync(source, output); };
const sha = (file) => crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex");
rm(stage); mkdir(stage);
const postV1 = fs.readdirSync(path.join(root, "data/staging/post_v1")).filter((name) => /^AYODHYA_S\d+_SOURCE_BACKED_RECORDS\.json$/.test(name)).sort((a, b) => Number(a.match(/S(\d+)/)[1]) - Number(b.match(/S(\d+)/)[1]));
for (const name of postV1) cp(`data/staging/post_v1/${name}`, `staging/records/${name}`);
cp("data/staging/physical/STAGING_RECORDS.json", "staging/records/STAGING_RECORDS.json");
for (const file of ["SOURCE_LEDGER_V3.json", "S34_SOURCE_SCOPE_EVIDENCE.json", "S35_SOURCE_SCOPE_EVIDENCE.json"]) cp(file, `sources/${file}`);
for (const file of ["V1_5_RECONCILIATION_PREVIEW_V3.json", "TEXTUAL_VARIANCE_LEDGER_V2.json"]) cp(file, `reconciliation/${file}`);
cp("TAMIL_EDITORIAL_REVIEW_QUEUE_V3.json", "tamil-review/TAMIL_EDITORIAL_REVIEW_QUEUE_V3.json");
for (const file of ["POST_V1_EDITORIAL_INDEX_V3.json", "RAMAVERSE-CANONICAL-MOBILE-PACK-v1.5.0-CANDIDATE-METADATA-V3.json"]) cp(file, `indexes/${file}`);
cp("POST_V1_STAGING_KNOWLEDGE_GRAPH_V3.json", "knowledge-graph/POST_V1_STAGING_KNOWLEDGE_GRAPH_V3.json");
for (const file of ["PRE_RUN_AUTHORITY_STATE_V3.json", "POST_RUN_AUTHORITY_STATE_V3.json", "POST_V1_STAGING_PHYSICAL_AUDIT_V3.json", "POST_V1_STAGING_VALIDATION_V3.json", "RELATIONAL_DIALOGUE_EVIDENCE_V3.json", "RAMA_LIFE_EVENT_DERIVATION_V3.json", "RAMAVERSE_STAGING_MASTER_LEDGER_V3.json", "EXACT_PHYSICAL_CONTINUATION_V3.json", "RAMAVERSE_PROJECT_STATE.json"]) cp(file, `evidence/${file}`);
const continuation = `# RamaVerse Corpus Authority — V3 Continuation\n\nThe historical canonical baseline remains **550**. The physically validated staging corpus contains **248** quarantined records; published staging, public Search staging, public Ask staging, and public graph staging are all **0**. The next exact source point is **Valmiki Ramayana, Ayodhya Kanda, Sarga 36, verse 2.36.1**.\n\nContinue only through sequential, source-backed staging. Do not alter the frozen v1.4.0 mobile pack, the canonical baseline, or public corpus surfaces without formal reconciliation approval.\n`;
const handoff = `# RamaVerse V3 Handoff\n\nThis archive preserves V3 physical staging evidence for Ayodhya Kanda Sargas 34–35. Sarga 34 contains 21 new records and Sarga 35 contains 15, bringing physical staging to 248. The run created 36 editorial-ready Tamil drafts but makes **no human-review claim**. Sarga 35's embedded parental backstory is retained as source-review staging rather than verified lineage data.\n\nThe V3 validation gate passed with no duplicate IDs, unresolved source identifiers, missing required fields, staging publication, or public Search/Ask/graph exposure.\n`;
const manifest = { archiveId: "ramaverse-corpus-authority-post-v1-vnext-v3", generatedAt: new Date().toISOString(), canonicalBaseline: 550, physicalStaging: 248, stagingPublished: 0, nextExactSource: "Ayodhya Kanda / Sarga 36 / verse 2.36.1", includedSargas: postV1.map((name) => Number(name.match(/S(\d+)/)[1])), requiredDirectories: ["staging/records", "sources", "reconciliation", "tamil-review", "indexes", "knowledge-graph", "evidence", "docs"], archiveValidation: "Archive must be reopened after ZIP creation." };
mkdir(path.join(stage, "docs")); fs.writeFileSync(path.join(stage, "docs/CONTINUATION.md"), continuation); fs.writeFileSync(path.join(stage, "docs/HANDOFF.md"), handoff); fs.writeFileSync(path.join(stage, "docs/SOURCE_FREEZE_MANIFEST_V3.json"), JSON.stringify(manifest, null, 2) + "\n");
const files = []; const walk = (directory) => { for (const entry of fs.readdirSync(directory, { withFileTypes: true })) { const full = path.join(directory, entry.name); if (entry.isDirectory()) walk(full); else files.push(full); } }; walk(stage);
fs.writeFileSync(path.join(stage, "SHA256SUMS.txt"), files.map((file) => `${sha(file)}  ${path.relative(stage, file)}`).sort().join("\n") + "\n");
rm(zip); const zipped = spawnSync("zip", ["-q", "-r", zip, "."], { cwd: stage, encoding: "utf8" }); if (zipped.status !== 0) throw new Error(zipped.stderr || "zip failed");
const listed = spawnSync("unzip", ["-Z1", zip], { encoding: "utf8" }); if (listed.status !== 0) throw new Error(listed.stderr || "unzip listing failed");
const entries = listed.stdout.trim().split("\n").filter(Boolean); const required = ["staging/records/AYODHYA_S34_SOURCE_BACKED_RECORDS.json", "staging/records/AYODHYA_S35_SOURCE_BACKED_RECORDS.json", "sources/SOURCE_LEDGER_V3.json", "reconciliation/TEXTUAL_VARIANCE_LEDGER_V2.json", "tamil-review/TAMIL_EDITORIAL_REVIEW_QUEUE_V3.json", "indexes/RAMAVERSE-CANONICAL-MOBILE-PACK-v1.5.0-CANDIDATE-METADATA-V3.json", "knowledge-graph/POST_V1_STAGING_KNOWLEDGE_GRAPH_V3.json", "evidence/POST_RUN_AUTHORITY_STATE_V3.json", "docs/CONTINUATION.md", "docs/HANDOFF.md", "SHA256SUMS.txt"];
const missingRequiredEntries = required.filter((entry) => !entries.includes(entry)); const validation = { validationId: "ramaverse-v3-authority-archive-validation", generatedAt: new Date().toISOString(), archive: zip, sha256: sha(zip), entries: entries.length, missingRequiredEntries, reopened: true, valid: missingRequiredEntries.length === 0 && entries.length >= required.length };
fs.writeFileSync(path.join(root, "V3_AUTHORITY_ARCHIVE_VALIDATION.json"), JSON.stringify(validation, null, 2) + "\n");
console.log(JSON.stringify(validation, null, 2)); if (!validation.valid) process.exit(1);
