import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

const root = "/home/ubuntu/ramaverse";
const read = (relative) => JSON.parse(fs.readFileSync(path.join(root, relative), "utf8"));
const write = (relative, value) => fs.writeFileSync(path.join(root, relative), JSON.stringify(value, null, 2) + "\n");
const hash = (relative) => crypto.createHash("sha256").update(fs.readFileSync(path.join(root, relative))).digest("hex");
const names = fs.readdirSync(path.join(root, "data/staging/post_v1")).filter((name) => /^AYODHYA_S\d+_SOURCE_BACKED_RECORDS\.json$/.test(name)).sort((a, b) => Number(a.match(/S(\d+)/)[1]) - Number(b.match(/S(\d+)/)[1]));
const payloads = [{ path: "data/staging/physical/STAGING_RECORDS.json", records: read("data/staging/physical/STAGING_RECORDS.json") }, ...names.map((name) => ({ path: `data/staging/post_v1/${name}`, batch: read(`data/staging/post_v1/${name}`) }))];
for (const payload of payloads.slice(1)) payload.records = payload.batch.records ?? [];
const records = payloads.flatMap((payload) => payload.records.map((record) => ({ ...record, _payload: payload.path })));
const duplicateIds = [...new Set(records.map((record) => record.candidate_id).filter((id, index, all) => all.indexOf(id) !== index))].sort();
const s32 = read("data/staging/post_v1/AYODHYA_S32_SOURCE_BACKED_RECORDS.json"), s33 = read("data/staging/post_v1/AYODHYA_S33_SOURCE_BACKED_RECORDS.json");
if (s32.records.length !== s32.recordCount || s33.records.length !== s33.recordCount || duplicateIds.length) throw new Error("S32/S33 count or duplicate gate failed");
const priorSources = read("SOURCE_LEDGER_VNEXT.json");
const newSources = [
  { source_id: "src-valmiki-ayodhya-s32-stotranidhi", title: "Valmiki Ramayana — Ayodhya Kanda — Sarga 32", repository: "Stotra Nidhi", edition_or_recension: "Traditional digital IAST text presentation", language: "Sanskrit (IAST)", sourceType: "PRIMARY_TEXT_DIGITAL_RENDITION", kanda: "Ayodhya Kanda", sarga: 32, verse_range: "2.32.1–2.32.45", url: "https://stotranidhi.com/en/ayodhya-kanda-sarga-32-in-english/", accessedAt: "2026-08-19", rights_status: "External reference; staging stores only original structured paraphrases.", tradition: "Valmiki", confidence: "high", variant_notes: "Primary locator; independently cross-checked at verse 21 and against a grouped-display presentation." },
  { source_id: "src-valmiki-ayodhya-s32-vedapath-v21-crosscheck", title: "Valmiki Ramayana 2.32.21 — verse cross-check", repository: "Vedapath", edition_or_recension: "Digital verse presentation", language: "Sanskrit with English interface", sourceType: "PRIMARY_TEXT_DIGITAL_CROSSCHECK", kanda: "Ayodhya Kanda", sarga: 32, verse_range: "2.32.21", url: "https://vedapath.app/en/ramayana/ayodhya-kanda/32/21", accessedAt: "2026-08-19", rights_status: "External reference; no continuous source text reproduced.", tradition: "Valmiki", confidence: "medium", variant_notes: "Confirms a pivotal distribution-context locator." },
  { source_id: "src-valmiki-ayodhya-s32-ramayanainfo-crosscheck", title: "Ramayana.info — Ayodhya Kanda Sarga 32", repository: "Ramayana.info", edition_or_recension: "Digital Sanskrit and English presentation", language: "Sanskrit with English", sourceType: "PRIMARY_TEXT_DIGITAL_CROSSCHECK", kanda: "Ayodhya Kanda", sarga: 32, verse_range: "Displays through 2.32.45 in 40 grouped units", url: "https://ramayana.info/story/ayodhya/32/", accessedAt: "2026-08-19", rights_status: "External reference; no continuous source text reproduced.", tradition: "Valmiki", confidence: "medium", variant_notes: "Presentation counts 40 grouped shloka units while visible locators extend through 45; retained as a display/segmentation variance." },
  { source_id: "src-valmiki-ayodhya-s33-sanskritdocuments", title: "Valmiki Ramayana — Ayodhya Kanda — Sarga 33", repository: "SanskritDocuments.org", edition_or_recension: "Traditional digital Sanskrit rendition with English word-for-word translation", language: "Sanskrit with English translation", sourceType: "PRIMARY_TEXT_DIGITAL_RENDITION", kanda: "Ayodhya Kanda", sarga: 33, verse_range: "2.33.1–2.33.31", url: "https://sanskritdocuments.org/sites/valmikiramayan/ayodhya/sarga33/ayodhyaroman33.htm", accessedAt: "2026-08-19", rights_status: "External reference; staging stores only original structured paraphrases.", tradition: "Valmiki", confidence: "high", variant_notes: "Primary 31-verse chapter locator." },
  { source_id: "src-valmiki-ayodhya-s33-stotranidhi-crosscheck", title: "Ayodhya Kanda Sarga 33 — chapter cross-check", repository: "Stotra Nidhi", edition_or_recension: "Traditional digital IAST text presentation", language: "Sanskrit (IAST)", sourceType: "PRIMARY_TEXT_DIGITAL_CROSSCHECK", kanda: "Ayodhya Kanda", sarga: 33, verse_range: "2.33.1–2.33.31", url: "https://stotranidhi.com/en/ayodhya-kanda-sarga-33-in-english/", accessedAt: "2026-08-19", rights_status: "External reference; no continuous source text reproduced.", tradition: "Valmiki", confidence: "medium", variant_notes: "Confirms the 31-verse chapter scope." },
  { source_id: "src-valmiki-ayodhya-s33-vedapath-v28-crosscheck", title: "Valmiki Ramayana 2.33.28 — verse cross-check", repository: "Vedapath", edition_or_recension: "Digital verse presentation", language: "Sanskrit with English interface", sourceType: "PRIMARY_TEXT_DIGITAL_CROSSCHECK", kanda: "Ayodhya Kanda", sarga: 33, verse_range: "2.33.28", url: "https://vedapath.app/en/ramayana/ayodhya-kanda/33/28", accessedAt: "2026-08-19", rights_status: "External reference; no continuous source text reproduced.", tradition: "Valmiki", confidence: "medium", variant_notes: "Confirms the palace-and-Sumantra context." }
];
const knownSourceIds = new Set(priorSources.sources.map((source) => source.source_id));
const sourceLedger = { ...priorSources, ledgerId: "ramaverse-master-source-ledger-v2", generatedAt: new Date().toISOString(), sources: [...priorSources.sources, ...newSources.filter((source) => !knownSourceIds.has(source.source_id))] };
write("SOURCE_LEDGER_V2.json", sourceLedger);
const ledger = { ledgerId: "ramaverse-website-staging-master-ledger-v2", generatedAt: new Date().toISOString(), mode: "physical-records-only", historicalCanonicalBaseline: 550, stagingPublished: 0, physicallyAvailableUniqueRecords: records.length, candidateRecordsNotCountedAsPhysicalStaging: 7, recordPayloads: payloads.map((payload) => ({ path: payload.path, records: payload.records.length })), duplicates: { candidateIds: duplicateIds, count: duplicateIds.length }, latestVerifiedCoverage: { kanda: "Ayodhya Kanda", sarga: 33, verseRange: "2.33.1–2.33.31", status: "PHYSICAL_STAGING_SOURCE_BACKED", editionVariance: "No numbering variance identified for Sarga 33." }, nextAcquisitionPoint: { kanda: "Ayodhya Kanda", sarga: 34, verseRange: "2.34.1 onward", status: "SOURCE_PROCUREMENT_PENDING" }, publicSurfacePolicy: { search: "CANONICAL_ONLY", ask: "CANONICAL_ONLY", stagingExposure: 0 } };
write("RAMAVERSE_STAGING_MASTER_LEDGER_V2.json", ledger);
write("EXACT_PHYSICAL_CONTINUATION_V2.json", { ledgerId: "ramaverse-exact-physical-continuation-v2", generatedAt: new Date().toISOString(), historicalCanonicalBaseline: 550, physicalStagingCount: records.length, last_fully_acquired_kanda: "Ayodhya Kanda", last_fully_acquired_sarga: 33, last_fully_acquired_verse: "2.33.31", next_unacquired_verse: "2.34.1", source_id: "src-valmiki-ayodhya-s33-sanskritdocuments", source_locator: "SanskritDocuments, Valmiki Ramayana, Ayodhya Kanda, Sarga 33, verses 2.33.1–2.33.31", supporting_record_ids: ["stg-postv1-ayodhyakanda-s33-sarga-001", "stg-postv1-ayodhyakanda-s33-source-001"], duplicate_prevention: "Next acquisition begins only at Sarga 34, verse 2.34.1; all source variants remain separate in TEXTUAL_VARIANCE_LEDGER.json." });
write("S32_SOURCE_SCOPE_EVIDENCE.json", { evidenceId: "ramaverse-s32-source-scope-v1", generatedAt: new Date().toISOString(), primarySource: { sourceId: "src-valmiki-ayodhya-s32-stotranidhi", verseRange: "2.32.1–2.32.45", url: "https://stotranidhi.com/en/ayodhya-kanda-sarga-32-in-english/" }, crossChecks: [{ sourceId: "src-valmiki-ayodhya-s32-vedapath-v21-crosscheck", verse: "2.32.21" }, { sourceId: "src-valmiki-ayodhya-s32-ramayanainfo-crosscheck", observed: "Visible locators through 2.32.45; page labels 40 grouped display units." }], result: "PASS" });
write("S33_SOURCE_SCOPE_EVIDENCE.json", { evidenceId: "ramaverse-s33-source-scope-v1", generatedAt: new Date().toISOString(), primarySource: { sourceId: "src-valmiki-ayodhya-s33-sanskritdocuments", verseRange: "2.33.1–2.33.31", url: "https://sanskritdocuments.org/sites/valmikiramayan/ayodhya/sarga33/ayodhyaroman33.htm" }, crossChecks: [{ sourceId: "src-valmiki-ayodhya-s33-stotranidhi-crosscheck", chapterScope: "2.33.1–2.33.31" }, { sourceId: "src-valmiki-ayodhya-s33-vedapath-v28-crosscheck", verse: "2.33.28" }], result: "PASS" });
const varianceEntries = [
  { variance_id: "var-valmiki-ayodhya-s31-001", kanda: "Ayodhya Kanda", sarga: 31, primary_source_id: "src-valmiki-ayodhya-s31-sanskritdocuments", primary_locator: "2.31.1–2.31.35", variant_source_id: "src-valmiki-ayodhya-s31-stotranidhi-crosscheck", variant_locator: "Stotra Nidhi verses 1–37, with marked additions after verse 19", variance_type: "ADDITIONAL_VERSE_NUMBERING_PRESENTATION", confidence: "medium", handling: "RETAIN_SEPARATELY_DO_NOT_SILENTLY_MERGE", status: "AWAITING_EDITORIAL_RECONCILIATION" },
  { variance_id: "var-valmiki-ayodhya-s32-001", kanda: "Ayodhya Kanda", sarga: 32, primary_source_id: "src-valmiki-ayodhya-s32-stotranidhi", primary_locator: "2.32.1–2.32.45", variant_source_id: "src-valmiki-ayodhya-s32-ramayanainfo-crosscheck", variant_locator: "Page labels 40 grouped display units while showing locators through 2.32.45", variance_type: "DISPLAY_GROUPING_OR_SEGMENTATION", confidence: "medium", handling: "RETAIN_SEPARATELY_DO_NOT_NORMALIZE_NUMBERING", status: "AWAITING_EDITORIAL_RECONCILIATION" }
];
write("TEXTUAL_VARIANCE_LEDGER.json", { ledgerId: "ramaverse-textual-variance-ledger-v1", generatedAt: new Date().toISOString(), scope: "Source presentation and numbering differences only; no variant material is promoted or silently merged.", entries: varianceEntries, count: varianceEntries.length });
const stateFor = (record) => { const raw = String(record.tamil_review_status ?? record.review_status ?? "").toUpperCase(); if (raw === "EDITORIAL_DRAFT_READY_FOR_HUMAN_REVIEW") return raw; if (raw.includes("SOURCE_TAMIL")) return "SOURCE_TRANSLATION_AVAILABLE"; if (raw.includes("TRANSLITERATION")) return "TRANSLITERATION_ONLY"; if (raw.includes("NOT_AVAILABLE")) return "NOT_AVAILABLE"; return "MACHINE_DRAFT_NEEDS_REVIEW"; };
const priorityFor = (record) => ({ DIALOGUE: "P1", HISTORICAL_TEXTUAL_NORM: "P2", THEME: "P2", EVENT: "P2", SARGA: "P2", RELATIONSHIP: "P3", CHARACTER_REFERENCE: "P3", JOURNEY: "P3", PLACE: "P3", OBJECT_REFERENCE: "P3", VERSE_SECTION: "P3", SOURCE_REFERENCE: "P4" }[record.record_type] ?? "P4");
const queueRecords = records.map((record) => ({ record_id: record.candidate_id, record_type: record.record_type, source_locator: record.source_locator ?? record.canonical_source_locator ?? null, current_tamil_text: record.tamil_draft ?? record.tamil_explanation ?? null, translation_status: stateFor(record), priority: priorityFor(record), human_reviewed: false, editorial_work: stateFor(record) === "EDITORIAL_DRAFT_READY_FOR_HUMAN_REVIEW" ? "Source-faithful Tamil editorial draft improved for grammar, punctuation, name consistency, and safeguard clarity; human review remains required." : "Existing Tamil machine draft retained for human editorial refinement; no human-review claim is made.", merge_state: record.merge_state ?? "awaiting_v1_4_0_reconciliation", publication_state: "STAGING_QUARANTINE_ONLY" })).sort((a, b) => a.priority.localeCompare(b.priority) || a.record_id.localeCompare(b.record_id));
const by = (items, key) => items.reduce((out, item) => ({ ...out, [item[key]]: (out[item[key]] ?? 0) + 1 }), {});
write("TAMIL_EDITORIAL_REVIEW_QUEUE_V2.json", { queueId: "ramaverse-tamil-editorial-review-queue-v2", generatedAt: new Date().toISOString(), scope: "All physical staging only. No entry is HUMAN_REVIEWED or publicly published.", records: queueRecords, countsByTranslationState: by(queueRecords, "translation_status"), countsByPriority: by(queueRecords, "priority"), editorialDraftsImprovedThisRun: queueRecords.filter((record) => record.translation_status === "EDITORIAL_DRAFT_READY_FOR_HUMAN_REVIEW").length, humanReviewedCount: 0 });
const typeCounts = by(records, "record_type"), priorCandidates = read("POST_V1_RECONCILIATION_CANDIDATES.json").candidates ?? [];
write("V1_5_RECONCILIATION_PREVIEW_V2.json", { previewId: "ramaverse-v1.5-reconciliation-preview-v2", generatedAt: new Date().toISOString(), status: "EDITORIAL_PREVIEW_ONLY_NOT_PRODUCTION_READY", historicalCanonicalBaseline: 550, stagingPublished: 0, physicalStagingRecords: records.length, counts: { NEW_CANONICAL_CANDIDATE: records.length, ENRICH_EXISTING: 0, DUPLICATE: duplicateIds.length, VARIANT: varianceEntries.length, CONFLICT: 0, SOURCE_REVIEW: records.length, TAMIL_REVIEW: queueRecords.filter((record) => !record.human_reviewed).length, REJECTED: 0 }, pendingHistoricalCandidates: priorCandidates.length, guardrails: ["No staging record is added to the frozen 550 canonical baseline.", "No staging record is exposed to public Search, Ask, public graph, or the frozen mobile pack.", "TEXTUAL_VARIANCE_LEDGER entries require editorial reconciliation before any normalized assertion."] });
write("RAMAVERSE-CANONICAL-MOBILE-PACK-v1.5.0-CANDIDATE-METADATA-V2.json", { metadataId: "ramaverse-v1.5.0-candidate-metadata-v2", generatedAt: new Date().toISOString(), status: "METADATA_ONLY_NOT_A_MOBILE_PACK", approvedMobilePack: "RAMAVERSE-CANONICAL-MOBILE-PACK-v1.4.0-FINAL-v2.zip", approvedPackModified: false, stagingRecordCount: records.length, newThisRunCandidateIds: [...s32.records, ...s33.records].map((record) => record.candidate_id), eligibility: "Formal v1.5 reconciliation, source review, and human Tamil editorial approval are all required before any production pack is generated.", stagingPublished: 0, publicExposure: 0 });
const relationEdges = records.filter((record) => record.record_type === "RELATIONSHIP" && record.subject && record.object).map((record) => ({ from: record.subject, to: record.object, relation: record.relation, evidence_id: record.candidate_id, source_id: record.source_id, verse_locator: record.verse_locator })), dialogueEdges = records.filter((record) => record.record_type === "DIALOGUE").map((record) => ({ from: record.speaker, to: record.listener, relation: "SPEAKS_TO", evidence_id: record.candidate_id, source_id: record.source_id, verse_locator: record.verse_locator }));
write("POST_V1_STAGING_KNOWLEDGE_GRAPH_V2.json", { graphId: "ramaverse-post-v1-staging-knowledge-graph-v2", generatedAt: new Date().toISOString(), visibility: "EDITORIAL_ONLY_STAGING", publicGraphExposure: 0, nodes: records.map((record) => ({ id: record.candidate_id, type: record.record_type, source_id: record.source_id ?? null, staging_state: "QUARANTINED" })), edges: [...relationEdges, ...dialogueEdges], safeguards: "Public knowledge graph remains canonical-only." });
write("POST_V1_EDITORIAL_INDEX_V2.json", { indexId: "ramaverse-post-v1-editorial-index-v2", generatedAt: new Date().toISOString(), visibility: "EDITORIAL_ONLY_STAGING", canonicalBaseline: 550, stagingRecords: records.length, publicSearchEntries: 0, publicAskEntries: 0, byRecordType: typeCounts, bySarga: by(records.filter((record) => record.sarga), "sarga") });
write("RELATIONAL_DIALOGUE_EVIDENCE_V2.json", { evidenceId: "ramaverse-relational-dialogue-evidence-v2", generatedAt: new Date().toISOString(), visibility: "EDITORIAL_ONLY_STAGING", s32: { dialogues: s32.records.filter((record) => record.record_type === "DIALOGUE").map((record) => record.candidate_id), relationships: s32.records.filter((record) => record.record_type === "RELATIONSHIP").map((record) => record.candidate_id), events: s32.records.filter((record) => record.record_type === "EVENT").map((record) => record.candidate_id) }, s33: { dialogues: s33.records.filter((record) => record.record_type === "DIALOGUE").map((record) => record.candidate_id), relationships: s33.records.filter((record) => record.record_type === "RELATIONSHIP").map((record) => record.candidate_id), events: s33.records.filter((record) => record.record_type === "EVENT").map((record) => record.candidate_id) }, boundary: "All records are source-bound narrative evidence; no item is a public recommendation or canonical claim." });
const state = read("RAMAVERSE_PROJECT_STATE.json");
write("RAMAVERSE_PROJECT_STATE.json", { ...state, RV_01_staging_count: records.length, staging_published: 0, staging_files: [...new Set([...state.staging_files, "data/staging/post_v1/AYODHYA_S32_SOURCE_BACKED_RECORDS.json", "data/staging/post_v1/AYODHYA_S33_SOURCE_BACKED_RECORDS.json"])], stable_id_registries: [...new Set([...state.stable_id_registries, "RAMAVERSE_STAGING_MASTER_LEDGER_V2.json", "TEXTUAL_VARIANCE_LEDGER.json"])], RV_01_continuation: "Ayodhya Kanda Sarga 34, verse 2.34.1 onward", source_clusters: [...new Set([...state.source_clusters, "Valmiki Ramayana / Ayodhya Kanda / Sargas 32–33 physical source-backed staging"])], latest_batch_ids: ["AYODHYA_S32_SOURCE_BACKED_RECORDS", "AYODHYA_S33_SOURCE_BACKED_RECORDS", "TEXTUAL_VARIANCE_LEDGER", "TAMIL_EDITORIAL_REVIEW_QUEUE_V2"], task_output_map: { ...state.task_output_map, physical_ledger: "RAMAVERSE_STAGING_MASTER_LEDGER_V2.json", continuation: "EXACT_PHYSICAL_CONTINUATION_V2.json", source_ledger: "SOURCE_LEDGER_V2.json", tamil_queue: "TAMIL_EDITORIAL_REVIEW_QUEUE_V2.json", variance_ledger: "TEXTUAL_VARIANCE_LEDGER.json", corpus_archive: "RAMAVERSE-CORPUS-AUTHORITY-POST-V1-vNEXT.zip" }, SHA256: { ...state.SHA256, s32_staging_payload: hash("data/staging/post_v1/AYODHYA_S32_SOURCE_BACKED_RECORDS.json"), s33_staging_payload: hash("data/staging/post_v1/AYODHYA_S33_SOURCE_BACKED_RECORDS.json"), staging_ledger_v2: hash("RAMAVERSE_STAGING_MASTER_LEDGER_V2.json") }, exact_next_point: "Ayodhya Kanda / Sarga 34 / verse 2.34.1", updated_at: new Date().toISOString() });
console.log(JSON.stringify({ physicalStaging: records.length, s32Records: s32.records.length, s33Records: s33.records.length, sources: sourceLedger.sources.length, editorialDraftsImproved: queueRecords.filter((record) => record.translation_status === "EDITORIAL_DRAFT_READY_FOR_HUMAN_REVIEW").length, variants: varianceEntries.length, duplicateIds, status: "PASS" }, null, 2));
