import fs from "node:fs";
import path from "node:path";

const root = "/home/ubuntu/ramaverse";
const read = (relative) => JSON.parse(fs.readFileSync(path.join(root, relative), "utf8"));
const names = fs.readdirSync(path.join(root, "data/staging/post_v1")).filter((name) => /^AYODHYA_S\d+_SOURCE_BACKED_RECORDS\.json$/.test(name)).sort((a, b) => Number(a.match(/S(\d+)/)[1]) - Number(b.match(/S(\d+)/)[1]));
const payloads = [{ path: "data/staging/physical/STAGING_RECORDS.json", records: read("data/staging/physical/STAGING_RECORDS.json") }, ...names.map((name) => ({ path: `data/staging/post_v1/${name}`, records: read(`data/staging/post_v1/${name}`).records ?? [] }))];
const records = payloads.flatMap((payload) => payload.records), ids = records.map((record) => record.candidate_id).filter(Boolean), duplicateIds = [...new Set(ids.filter((id, index) => ids.indexOf(id) !== index))].sort();
const ledger = read("RAMAVERSE_STAGING_MASTER_LEDGER_V2.json"), continuation = read("EXACT_PHYSICAL_CONTINUATION_V2.json"), postRun = read("POST_RUN_AUTHORITY_STATE_V2.json"), sources = read("SOURCE_LEDGER_V2.json"), tamil = read("TAMIL_EDITORIAL_REVIEW_QUEUE_V2.json"), variants = read("TEXTUAL_VARIANCE_LEDGER.json");
const state = { stateId: "ramaverse-pre-run-authority-state-v3", generatedAt: new Date().toISOString(), authorityRule: "Derived exclusively from physical payloads and current V2 ledger, continuation, post-run, source, Tamil, and variance evidence.", canonicalProduction: 550, physicalStaging: records.length, ledgerStaging: ledger.physicallyAvailableUniqueRecords, physicalLedgerMatch: records.length === ledger.physicallyAvailableUniqueRecords && postRun.physicalLedgerMatch, uniqueIds: new Set(ids).size, duplicateIds, missingSourceIds: postRun.missingSourceIds, payloads: payloads.map((payload) => ({ path: payload.path, records: payload.records.length })), stagingPublished: ledger.stagingPublished, publicSearchStaging: ledger.publicSurfacePolicy.stagingExposure, publicAskStaging: ledger.publicSurfacePolicy.stagingExposure, latestFullyAcquired: { kanda: continuation.last_fully_acquired_kanda, sarga: continuation.last_fully_acquired_sarga, verse: continuation.last_fully_acquired_verse }, nextUnacquired: continuation.next_unacquired_verse, sourceCount: sources.sources.length, tamilReviewQueue: { count: tamil.records.length, translationStates: tamil.countsByTranslationState, humanReviewedCount: tamil.humanReviewedCount }, textualVariants: variants.count, acquisitionGate: records.length === 212 && records.length === ledger.physicallyAvailableUniqueRecords && duplicateIds.length === 0 && postRun.missingSourceIds.length === 0 && ledger.stagingPublished === 0 && ledger.publicSurfacePolicy.stagingExposure === 0 && continuation.next_unacquired_verse === "2.34.1" ? "PASS_START_AYODHYA_SARGA_34" : "NO_GO_USE_ACTUAL_PHYSICAL_CONTINUATION" };
fs.writeFileSync(path.join(root, "PRE_RUN_AUTHORITY_STATE_V3.json"), JSON.stringify(state, null, 2) + "\n");
console.log(JSON.stringify(state, null, 2));
if (state.acquisitionGate !== "PASS_START_AYODHYA_SARGA_34") process.exit(1);
