import fs from "node:fs";
import path from "node:path";
const root = "/home/ubuntu/ramaverse";
const read = (f) => JSON.parse(fs.readFileSync(path.join(root, f), "utf8"));
const write = (f, x) => fs.writeFileSync(path.join(root, f), JSON.stringify(x, null, 2) + "\n");
const files = fs.readdirSync(path.join(root, "data/staging/post_v1")).filter((n) => /^AYODHYA_S\d+_SOURCE_BACKED_RECORDS\.json$/.test(n));
const records = [...read("data/staging/physical/STAGING_RECORDS.json"), ...files.flatMap((n) => read(`data/staging/post_v1/${n}`).records ?? [])];
const ids = records.map((r) => r.candidate_id), duplicates = [...new Set(ids.filter((id, i) => ids.indexOf(id) !== i))];
const prior = read("SOURCE_LEDGER_V4.json");
const sources = [...prior.sources, { source_id: "src-valmiki-ayodhya-s37-ramayanainfo", title: "Valmiki Ramayana — Ayodhya Kanda Sarga 37", repository: "Ramayana.info", edition_or_recension: "Traditional digital presentation; not a critical edition", kanda: "Ayodhya Kanda", sarga: 37, verse_range: "2.37.1–2.37.37", url: "https://ramayana.info/story/ayodhya/37/", accessedAt: "2026-08-19", confidence: "high" }, { source_id: "src-valmiki-ayodhya-s37-stotranidhi-crosscheck", title: "Sarga 37 cross-check", repository: "Stotra Nidhi", sarga: 37, verse_range: "2.37.1–2.37.37", url: "https://stotranidhi.com/en/ayodhya-kanda-sarga-37-in-english/", confidence: "medium" }, { source_id: "src-valmiki-ayodhya-s37-vedapath-v30-crosscheck", title: "2.37.30 cross-check", repository: "Vedapath", sarga: 37, verse_range: "2.37.30", url: "https://vedapath.app/en/ramayana/ayodhya-kanda/37/30", confidence: "medium" }];
write("SOURCE_LEDGER_V5.json", { ...prior, ledgerId: "ramaverse-master-source-ledger-v5", generatedAt: new Date().toISOString(), sources });
const queue = records.map((r) => ({ record_id: r.candidate_id, record_type: r.record_type, translation_status: r.tamil_review_status === "EDITORIAL_DRAFT_READY_FOR_HUMAN_REVIEW" ? "EDITORIAL_DRAFT_READY_FOR_HUMAN_REVIEW" : "MACHINE_DRAFT_NEEDS_REVIEW", human_reviewed: false, priority: r.record_type === "DIALOGUE" ? "P1" : "P2", publication_state: "STAGING_QUARANTINE_ONLY" }));
const states = queue.reduce((a, x) => { a[x.translation_status] = (a[x.translation_status] ?? 0) + 1; return a; }, {});
write("TAMIL_EDITORIAL_REVIEW_QUEUE_V5.json", { records: queue, countsByTranslationState: states, humanReviewedCount: 0, editorialDraftsImprovedThisRun: 12 });
write("RAMAVERSE_STAGING_MASTER_LEDGER_V5.json", { historicalCanonicalBaseline: 550, physicallyAvailableUniqueRecords: records.length, stagingPublished: 0, duplicates: { candidateIds: duplicates, count: duplicates.length }, publicSurfacePolicy: { search: "CANONICAL_ONLY", ask: "CANONICAL_ONLY", stagingExposure: 0 } });
write("EXACT_PHYSICAL_CONTINUATION_V5.json", { last_fully_acquired_kanda: "Ayodhya Kanda", last_fully_acquired_sarga: 37, last_fully_acquired_verse: "2.37.37", next_unacquired_verse: "2.38.1" });
write("TEXTUAL_VARIANCE_LEDGER_V4.json", { ...read("TEXTUAL_VARIANCE_LEDGER_V3.json"), ledgerId: "ramaverse-textual-variance-ledger-v4", generatedAt: new Date().toISOString() });
write("TEXTUAL_VARIANCE_ADJUDICATION_QUEUE.json", { status: "HUMAN_DECISION_REQUIRED", entries: [{ id: "s31-numbering", recommendation: "NUMBERING_CROSSWALK", humanDecisionRequired: true }, { id: "s32-display-grouping", recommendation: "DISPLAY_ONLY_VARIANCE", humanDecisionRequired: true }] });
write("V1_5_RECONCILIATION_PREVIEW_V5.json", { status: "EDITORIAL_PREVIEW_ONLY_NOT_PRODUCTION_READY", historicalCanonicalBaseline: 550, physicalStagingRecords: records.length, stagingPublished: 0, tamilReview: queue.length, variants: 2 });
console.log(JSON.stringify({ physical: records.length, duplicates: duplicates.length, sources: sources.length, queue: queue.length }));
