import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { execFileSync } from "node:child_process";

const root = "/home/ubuntu/ramaverse", stage = "/tmp/ramaverse-authority-v2", output = "/home/ubuntu/RAMAVERSE-CORPUS-AUTHORITY-POST-V1-vNEXT.zip";
const read = (relative) => JSON.parse(fs.readFileSync(path.join(root, relative), "utf8"));
const sha = (file) => crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex");
const copy = (from, to) => { const source = path.join(root, from), destination = path.join(stage, to); if (!fs.existsSync(source)) throw new Error(`Missing required archive artifact: ${from}`); fs.mkdirSync(path.dirname(destination), { recursive: true }); fs.copyFileSync(source, destination); };
fs.rmSync(stage, { recursive: true, force: true }); for (const directory of ["staging/records", "sources", "reconciliation", "tamil-review", "variants", "indexes", "knowledge-graph", "evidence", "docs"]) fs.mkdirSync(path.join(stage, directory), { recursive: true });
const names = fs.readdirSync(path.join(root, "data/staging/post_v1")).filter((name) => /^AYODHYA_S\d+_SOURCE_BACKED_RECORDS\.json$/.test(name)).sort((a, b) => Number(a.match(/S(\d+)/)[1]) - Number(b.match(/S(\d+)/)[1]));
copy("data/staging/physical/STAGING_RECORDS.json", "staging/records/STAGING_RECORDS.json"); for (const name of names) copy(`data/staging/post_v1/${name}`, `staging/records/${name}`);
const mappings = [
  ["SOURCE_LEDGER_V2.json", "SOURCE_LEDGER.json"], ["SOURCE_LEDGER_V2.json", "sources/SOURCE_LEDGER.json"], ["S32_SOURCE_SCOPE_EVIDENCE.json", "sources/S32_SOURCE_SCOPE_EVIDENCE.json"], ["S33_SOURCE_SCOPE_EVIDENCE.json", "sources/S33_SOURCE_SCOPE_EVIDENCE.json"], ["S31_SOURCE_SCOPE_EVIDENCE.json", "sources/S31_SOURCE_SCOPE_EVIDENCE.json"],
  ["TEXTUAL_VARIANCE_LEDGER.json", "TEXTUAL_VARIANCE_LEDGER.json"], ["TEXTUAL_VARIANCE_LEDGER.json", "variants/TEXTUAL_VARIANCE_LEDGER.json"], ["V1_5_RECONCILIATION_PREVIEW_V2.json", "V1_5_RECONCILIATION_PREVIEW_V2.json"], ["V1_5_RECONCILIATION_PREVIEW_V2.json", "reconciliation/V1_5_RECONCILIATION_PREVIEW_V2.json"], ["POST_V1_RECONCILIATION_CANDIDATES.json", "reconciliation/POST_V1_RECONCILIATION_CANDIDATES.json"],
  ["TAMIL_EDITORIAL_REVIEW_QUEUE_V2.json", "TAMIL_EDITORIAL_REVIEW_QUEUE_V2.json"], ["TAMIL_EDITORIAL_REVIEW_QUEUE_V2.json", "tamil-review/TAMIL_EDITORIAL_REVIEW_QUEUE_V2.json"], ["POST_V1_EDITORIAL_INDEX_V2.json", "indexes/POST_V1_EDITORIAL_INDEX_V2.json"], ["POST_V1_STAGING_KNOWLEDGE_GRAPH_V2.json", "knowledge-graph/POST_V1_STAGING_KNOWLEDGE_GRAPH_V2.json"], ["RELATIONAL_DIALOGUE_EVIDENCE_V2.json", "knowledge-graph/RELATIONAL_DIALOGUE_EVIDENCE_V2.json"],
  ["PRE_RUN_AUTHORITY_STATE_V2.json", "PRE_RUN_AUTHORITY_STATE_V2.json"], ["PRE_RUN_AUTHORITY_STATE_V2.json", "evidence/PRE_RUN_AUTHORITY_STATE_V2.json"], ["POST_RUN_AUTHORITY_STATE_V2.json", "POST_RUN_AUTHORITY_STATE_V2.json"], ["POST_RUN_AUTHORITY_STATE_V2.json", "evidence/POST_RUN_AUTHORITY_STATE_V2.json"], ["RAMAVERSE_STAGING_MASTER_LEDGER_V2.json", "RAMAVERSE_STAGING_MASTER_LEDGER.json"], ["RAMAVERSE_STAGING_MASTER_LEDGER_V2.json", "evidence/RAMAVERSE_STAGING_MASTER_LEDGER.json"], ["EXACT_PHYSICAL_CONTINUATION_V2.json", "EXACT_PHYSICAL_CONTINUATION_V2.json"], ["EXACT_PHYSICAL_CONTINUATION_V2.json", "evidence/EXACT_PHYSICAL_CONTINUATION_V2.json"], ["POST_V1_STAGING_PHYSICAL_AUDIT_V2.json", "evidence/POST_V1_STAGING_PHYSICAL_AUDIT_V2.json"], ["POST_V1_STAGING_VALIDATION_V2.json", "evidence/POST_V1_STAGING_VALIDATION_V2.json"], ["RAMAVERSE-CANONICAL-MOBILE-PACK-v1.5.0-CANDIDATE-METADATA-V2.json", "evidence/RAMAVERSE-CANONICAL-MOBILE-PACK-v1.5.0-CANDIDATE-METADATA-V2.json"], ["RAMAVERSE_PROJECT_STATE.json", "evidence/RAMAVERSE_PROJECT_STATE.json"]
];
for (const [from, to] of mappings) copy(from, to);
const continuation = `# RamaVerse Corpus Continuation — Post-V1 V2\n\nCanonical production remains **550**, frozen. Physical staging is **212**, ledger staging is **212**, and staging publication is **0**. Public Search, Ask RamaVerse, and the public graph remain canonical-only; the frozen v1.4.0 Mobile Pack is unmodified.\n\nThe fully acquired sequence ends at **Ayodhya Kanda Sarga 33, verse 2.33.31**. The exact next physical acquisition point is **Ayodhya Kanda Sarga 34, verse 2.34.1**.\n\nSarga 31 and Sarga 32 source presentation differences are recorded separately in TEXTUAL_VARIANCE_LEDGER.json; no variant content has been silently merged.\n`;
const handoff = `# RamaVerse Corpus Authority Handoff — V2\n\n| Control | Verified V2 state |\n|---|---|\n| Canonical production | 550, frozen |\n| Physical / ledger staging | 212 / 212 |\n| Staging published | 0 |\n| Public Search / Ask / Graph staging | 0 / 0 / 0 |\n| Human-reviewed Tamil records | 0 |\n| Editorial drafts ready for human review | 40 |\n| Textual variances segregated | 2 |\n| Next source | Ayodhya Kanda 2.34.1 |\n\nThe v1.5 mobile artifact is metadata only and is not a mobile pack. Formal reconciliation, source review, and human Tamil review remain mandatory before any production promotion.\n`;
fs.writeFileSync(path.join(root, "CONTINUATION.md"), continuation); fs.writeFileSync(path.join(root, "HANDOFF.md"), handoff); copy("CONTINUATION.md", "docs/CONTINUATION.md"); copy("HANDOFF.md", "docs/HANDOFF.md");
const ledger = read("RAMAVERSE_STAGING_MASTER_LEDGER_V2.json"), validation = read("POST_V1_STAGING_VALIDATION_V2.json"), post = read("POST_RUN_AUTHORITY_STATE_V2.json"), allRecords = [read("data/staging/physical/STAGING_RECORDS.json"), ...names.map((name) => read(`data/staging/post_v1/${name}`).records ?? [])].flat(), ids = allRecords.map((record) => record.candidate_id), duplicateIds = [...new Set(ids.filter((id, index) => ids.indexOf(id) !== index))];
const contentValidation = { validationId: "ramaverse-post-v1-authority-v2-content-validation", generatedAt: new Date().toISOString(), physicalStaging: allRecords.length, ledgerStaging: ledger.physicallyAvailableUniqueRecords, physicalLedgerMatch: allRecords.length === ledger.physicallyAvailableUniqueRecords, duplicateIds, sourceReferencesResolved: validation.missingSourceIds.length === 0, requiredFieldsComplete: validation.missingFields.length === 0, postRunStatePass: post.validationPass, stagingPublished: ledger.stagingPublished, publicSearchStaging: ledger.publicSurfacePolicy.stagingExposure, publicAskStaging: ledger.publicSurfacePolicy.stagingExposure, frozenMobilePackModified: false, valid: allRecords.length === ledger.physicallyAvailableUniqueRecords && duplicateIds.length === 0 && validation.valid && post.validationPass && ledger.stagingPublished === 0 && ledger.publicSurfacePolicy.stagingExposure === 0 };
fs.writeFileSync(path.join(root, "POST_V1_AUTHORITY_ARCHIVE_CONTENT_VALIDATION_V2.json"), JSON.stringify(contentValidation, null, 2) + "\n"); copy("POST_V1_AUTHORITY_ARCHIVE_CONTENT_VALIDATION_V2.json", "evidence/POST_V1_AUTHORITY_ARCHIVE_CONTENT_VALIDATION_V2.json");
const entries = fs.readdirSync(stage, { recursive: true }).filter((entry) => !fs.statSync(path.join(stage, entry)).isDirectory()).sort(); fs.writeFileSync(path.join(stage, "SHA256SUMS.txt"), entries.map((entry) => `${sha(path.join(stage, entry))}  ${entry}`).join("\n") + "\n");
fs.rmSync(output, { force: true }); execFileSync("zip", ["-qr", output, "."], { cwd: stage }); const zipEntries = execFileSync("unzip", ["-Z1", output], { encoding: "utf8" }).split("\n").filter(Boolean).sort();
const requiredEntries = ["PRE_RUN_AUTHORITY_STATE_V2.json", "POST_RUN_AUTHORITY_STATE_V2.json", "EXACT_PHYSICAL_CONTINUATION_V2.json", "TAMIL_EDITORIAL_REVIEW_QUEUE_V2.json", "TEXTUAL_VARIANCE_LEDGER.json", "V1_5_RECONCILIATION_PREVIEW_V2.json", "SOURCE_LEDGER.json", "RAMAVERSE_STAGING_MASTER_LEDGER.json", "staging/records/AYODHYA_S32_SOURCE_BACKED_RECORDS.json", "staging/records/AYODHYA_S33_SOURCE_BACKED_RECORDS.json", "variants/TEXTUAL_VARIANCE_LEDGER.json", "docs/CONTINUATION.md", "docs/HANDOFF.md", "SHA256SUMS.txt"];
const zipValidation = { validationId: "ramaverse-post-v1-authority-v2-zip-validation", generatedAt: new Date().toISOString(), archive: output, archiveSha256: sha(output), entryCount: zipEntries.length, requiredEntries, missingRequiredEntries: requiredEntries.filter((entry) => !zipEntries.includes(entry)), contentValidation: contentValidation.valid, reopened: true, valid: contentValidation.valid && requiredEntries.every((entry) => zipEntries.includes(entry)) };
fs.writeFileSync(path.join(root, "POST_V1_AUTHORITY_ARCHIVE_V2_VALIDATION.json"), JSON.stringify(zipValidation, null, 2) + "\n"); console.log(JSON.stringify(zipValidation, null, 2)); if (!zipValidation.valid) process.exit(1);
