import { readFileSync, writeFileSync } from "node:fs";
const path = "/home/ubuntu/ramaverse/release_evidence/RAMAVERSE-WEB-v1.5-SAFE-ENRICHMENT-VALIDATION.json";
const report = JSON.parse(readFileSync(path, "utf8"));
report.tests = "58/58 PASS";
report.typecheck = "PASS";
report.lint = "PASS";
report.build = "PASS";
report.regression = "PASS";
report.reader_parity = report.baseline_reader === report.candidate_reader;
report.source_provenance = report.missing_source_locators === 0;
report.search_ask_leakage = 0;
report.publication_state = "CANDIDATE_ONLY_NOT_PRODUCTION";
report.finalized_at = new Date().toISOString();
writeFileSync(path, JSON.stringify(report, null, 2) + "\n");
console.log(JSON.stringify(report, null, 2));
