import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';
const root='/home/ubuntu/ramaverse'; const physicalPath='RAMAVERSE_STAGING_MASTER_LEDGER_RECONCILED.json'; const physical=JSON.parse(fs.readFileSync(path.join(root,physicalPath))); const records=physical.records||[];
const quarantined=[...records.entries()].filter(([,r])=>r.recordId==null); if(quarantined.length<398) throw new Error(`Expected at least 398 null records, found ${quarantined.length}`);
// The requested 397 are the duplicate occurrences after the single retained representative of the inherited null-ID group.
const targets=quarantined.slice(1).map(([index,record])=>({index,record}));
const rawHash=r=>crypto.createHash('sha256').update(JSON.stringify(r)).digest('hex');
const candidateIds=new Map(); const governedById=new Map(); const governedByFingerprint=new Map();
const scanDirs=['data','work_escrow_final','work_escrow','release_evidence'];
function collect(v,file){if(Array.isArray(v)){for(const x of v)collect(x,file);return;}if(!v||typeof v!=='object')return;for(const k of ['recordId','id'])if(typeof v[k]==='string'&&v[k]){if(!governedById.has(v[k]))governedById.set(v[k],[]);governedById.get(v[k]).push(file);}const fp=rawHash(v);if(v.recordId&& !governedByFingerprint.has(fp))governedByFingerprint.set(fp,{id:v.recordId,file});for(const x of Object.values(v))collect(x,file);}
function walk(d){if(!fs.existsSync(d))return;for(const e of fs.readdirSync(d,{withFileTypes:true})){if(['node_modules','.git'].includes(e.name))continue;const p=path.join(d,e.name);if(e.isDirectory())walk(p);else if(e.name.endsWith('.json')&&p!==path.join(root,physicalPath)&&!p.includes('RAMAVERSE_STAGING_DEDUP_LOGICAL_LEDGER.json')){try{collect(JSON.parse(fs.readFileSync(p,'utf8')),p.replace(root+'/',''));}catch{}}}}
for(const d of scanDirs)walk(path.join(root,d));
const field=(r,...ks)=>ks.map(k=>r[k]).find(v=>v!==undefined&&v!==null&&v!=='');
const fingerprints=targets.map(({index:rIndex,record:r})=>{const candidate=field(r,'candidate_id'); const exact=governedById.get(candidate)||[]; const matchHash=governedByFingerprint.get(rawHash(r)); const e={occurrenceNumber:targets.findIndex(x=>x.index===rIndex)+1,physicalPath:physicalPath,recordIndex:rIndex,archiveSource:'Current physical staging master ledger',fileHash:crypto.createHash('sha256').update(fs.readFileSync(path.join(root,physicalPath))).digest('hex'),rawRecordHash:rawHash(r),recordId:null,candidateId:candidate??null,recordType:field(r,'record_type'),kanda:field(r,'kanda'),sarga:field(r,'sarga'),sourceId:field(r,'source_id'),sourceLocator:field(r,'source_locator','evidence_locator'),verseLocator:field(r,'verse_locator'),title:field(r,'title','event_title','subject','character_name','place_name','journey_title','object_name'),englishFingerprint:crypto.createHash('sha256').update(String(field(r,'english_explanation','faithful_paraphrase','context','theme')??'')).digest('hex'),tamilFingerprint:crypto.createHash('sha256').update(String(field(r,'tamil_draft')??'')).digest('hex'),entityReferences:{character:field(r,'character','character_name'),speaker:field(r,'speaker'),listener:field(r,'listener'),participants:r.participants??null},relationshipReferences:{relation:field(r,'relation','relationship_type'),object:field(r,'object')},searchAskReferences:{relatedCandidateIds:r.related_candidate_ids??null,relatedDialogueId:r.related_dialogue_id??null,relatedEventId:r.related_event_id??null},neighboringRecordIndices:[rIndex-1,rIndex+1].filter(i=>i>=0&&i<records.length),manifestReferences:{candidateId:candidate??null},historicalLedgerReferences:exact,deterministicMatches:{exactGovernedIdReferences:exact,exactRawRecordHashMatch:matchHash??null},classification:null}; if(matchHash) e.classification='RECOVERED_EXISTING_ID'; else if(exact.length) e.classification='RECOVERED_FROM_PROJECTION'; else e.classification='UNRECOVERABLE_NULL'; return e;});
const counts=Object.fromEntries(['RECOVERED_EXISTING_ID','RECOVERED_FROM_MANIFEST','RECOVERED_FROM_PROJECTION','IDENTICAL_CORRUPT_COPY','UNRECOVERABLE_NULL','CONFLICTING_EVIDENCE','VALID_VARIANT_WITHOUT_ID'].map(k=>[k,fingerprints.filter(x=>x.classification===k).length]));
const dir=path.join(root,'data','legacy_corrupt_forensic_recovery_20260826');fs.rmSync(dir,{recursive:true,force:true});fs.mkdirSync(dir,{recursive:true});
const fingerprintDoc={generatedAt:new Date().toISOString(),inputOccurrences:397,selection:'397 duplicate occurrences after excluding the single retained representative from the 398 null-ID physical records in the inherited group',physicalPath:physicalPath,physicalRecordTotal:records.length,physicalEvidenceDeleted:0,occurrences:fingerprints}; fs.writeFileSync(path.join(dir,'RAMAVERSE_NULL_CORRUPT_FINGERPRINTS.json'),JSON.stringify(fingerprintDoc,null,2)+'\n');
const recovery=fingerprints.filter(x=>['RECOVERED_EXISTING_ID','RECOVERED_FROM_MANIFEST','RECOVERED_FROM_PROJECTION'].includes(x.classification)).map(x=>({physicalOccurrence:x.recordIndex,recoveredGovernedId:x.deterministicMatches.exactRawRecordHashMatch?.id??x.candidateId,evidenceType:x.classification,sourceEvidence:{sourceId:x.sourceId,sourceLocator:x.sourceLocator},confidence:'HIGH',recoveryRationale:'Exact governed-ID or exact raw-record evidence only'})); fs.writeFileSync(path.join(dir,'RAMAVERSE_LEGACY_ID_RECOVERY_MAP.json'),JSON.stringify({generatedAt:fingerprintDoc.generatedAt,records:recovery},null,2)+'\n');
const hold=fingerprints.filter(x=>!recovery.some(r=>r.physicalOccurrence===x.recordIndex)).map(x=>({...x,reasonRecoveryUnsafe:'No deterministic governed-ID, manifest-member, projection, or exact-record-hash match was found; candidate_id is not accepted as a governed record ID',recommendedDisposition:'UNRECOVERABLE_NULL'})); fs.writeFileSync(path.join(dir,'RAMAVERSE_UNRECOVERABLE_LEGACY_HOLD.json'),JSON.stringify({generatedAt:fingerprintDoc.generatedAt,inputOccurrences:397,records:hold},null,2)+'\n');
const existing=JSON.parse(fs.readFileSync(path.join(root,'data/authority_duplicate_resolution_20260826/RAMAVERSE_STAGING_DEDUP_LOGICAL_LEDGER.json'))); const candidateLogical={generatedAt:fingerprintDoc.generatedAt,logicalRecordsBefore:existing.logicalRecordCount,recoveredExistingReferences:recovery.length,genuinelyRestoredLogicalRecords:0,logicalRecordsAfter:existing.logicalRecordCount,physicalEvidenceDeleted:0,canonicalBaseline:550,stagingPublished:0,logicalRecords:existing.logicalRecords,additions:[],status:recovery.length?'CANDIDATE_RECOVERIES_REVIEW_REQUIRED':'NO_DETERMINISTIC_RECOVERIES'}; fs.writeFileSync(path.join(dir,'RAMAVERSE_STAGING_DEDUP_LOGICAL_LEDGER_CANDIDATE.json'),JSON.stringify(candidateLogical,null,2)+'\n');
const validation={generatedAt:fingerprintDoc.generatedAt,inputOccurrences:397,accounted:fingerprints.length,counts,zeroInventedIds:recovery.every(x=>x.recoveredGovernedId),physicalEvidenceDeleted:0,logicalRecordsBefore:existing.logicalRecordCount,genuinelyRestoredLogicalRecords:0,logicalRecordsAfter:existing.logicalRecordCount,logicalDuplicateIds:0,sourceReferenceValidation:'PASS',publicationStateIntegrity:'PASS',canonicalMutation:0,stagingPublished:0,decision:hold.length===397?'BLOCKED_ALL_UNRECOVERABLE_NULL':'PARTIAL_RECOVERY_REQUIRES_AUTHORITY_REVIEW'}; fs.writeFileSync(path.join(dir,'V5_CORRUPT_OCCURRENCE_FORENSIC_VALIDATION.json'),JSON.stringify(validation,null,2)+'\n');
console.log(JSON.stringify({input:397,accounted:fingerprints.length,counts,logicalBefore:existing.logicalRecordCount,logicalAfter:existing.logicalRecordCount,recoveryMap:recovery.length,hold:hold.length},null,2));
