import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';
const root='/home/ubuntu/ramaverse'; const out=path.join(root,'release_evidence','v5_recovery_20260826'); fs.mkdirSync(out,{recursive:true});
const inspect=(p)=>{try{const x=JSON.parse(fs.readFileSync(path.join(root,p))); const count=Array.isArray(x)?x.length:(x.records?.length??x.documents?.length??x.items?.length??x.edges?.length??x.connections?.length??null); return {path:p,count,keys:Object.keys(x).slice(0,12),sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex')};}catch{return null}};
const sources=['work_escrow_final/candidate_v4_work/search_index.json','work_escrow_final/candidate_v4_work/ask_index.json','work_escrow_final/mobile_candidate_pack_v3/search_index.json','work_escrow_final/mobile_candidate_pack_v3/ask_index.json','work_escrow_final/RAMAVERSE_STAGING_MASTER_LEDGER_V32.json','work_escrow_final/RAMAVERSE_POST_V1_MASTER_AUTHORITY.json','work_escrow_final/RAMAVERSE_STAGING_MASTER_LEDGER_RECONCILED.json'];
const candidates=sources.map(inspect).filter(Boolean);
const map={generatedAt:new Date().toISOString(),websiteAuthorityExpected:{search:922,ask:922,reader:645,entityConnections:3500,stagingPublished:0},physicalCandidates:candidates,deterministicReconstruction:{possible:false,reason:'No single physical Website authority set contains the required Search 922, Ask 922, Reader 645, and Entity Connections 3500 projections with complete provenance and matching schemas. Available projection files are incomplete or represent staging ledgers, so missing portions cannot be fabricated.',requiredCountsPhysicallySupported:false},identityChecks:{canonicalIds:'NOT_PROVEN_FOR_REQUIRED_PROJECTIONS',sourceIds:'NOT_PROVEN_FOR_REQUIRED_PROJECTIONS',aliases:'NOT_PROVEN',relationships:'NOT_PROVEN',readerRefs:'NOT_PROVEN',danglingIds:'NOT_PROVEN'},governance:{canonicalBaseline:550,stagingPublished:0,websiteModified:false,mobileModified:false,deployment:'NOT_PERFORMED'},decision:'V5_RECOVERY_BLOCKED_SOURCE_INCOMPLETE'};
fs.writeFileSync(path.join(out,'V5_WEBSITE_SOURCE_PROVENANCE_MAP.json'),JSON.stringify(map,null,2)+'\n');
const validation={generatedAt:map.generatedAt,search:922,ask:922,reader:645,entityConnections:3500,staging:0,placeholders:'NOT_PROVEN',templateViolations:'NOT_PROVEN',danglingIds:'NOT_PROVEN',provenance:'FAIL_SOURCE_INCOMPLETE',memberHashes:'NOT_APPLICABLE',v5Recovery:'BLOCKED',decision:'V5_RECOVERY_BLOCKED_SOURCE_INCOMPLETE'};
for(const [n,x] of Object.entries({V5_RECOVERY_VALIDATION:validation,V5_RECORD_COUNT_AUDIT:{expected:map.websiteAuthorityExpected,physicalCandidates:candidates},V5_TEMPLATE_DETECTION_REPORT:{status:'NOT_RUN_BEYOND_SOURCE_FORENSICS',reason:'Source set incomplete'},V5_REFERENTIAL_INTEGRITY_AUDIT:{status:'BLOCKED_SOURCE_INCOMPLETE'},V5_MEMBER_HASHES:{status:'NOT_APPLICABLE'}})) fs.writeFileSync(path.join(out,`${n}.json`),JSON.stringify(x,null,2)+'\n');
fs.writeFileSync(path.join(out,'RECOVERY_METHOD.md'),'# V5 Recovery Method\n\nThe current Website workspace was scanned without modifying Website, Mobile, canonical records, staging publication, deployment, GitLab, DNS, EAS, or AAB. Candidate projection files were inspected by physical path, schema keys, record counts, and SHA-256. Because the required four datasets are not available as a single complete provenance-preserving set, deterministic V5 reconstruction is blocked. No missing records are fabricated.\n\n## Decision\n\n`V5_RECOVERY_BLOCKED_SOURCE_INCOMPLETE`\n');
const work=path.join(out,'work'); fs.rmSync(work,{recursive:true,force:true}); fs.mkdirSync(work,{recursive:true}); for(const f of fs.readdirSync(out)){if(f==='work'||f.endsWith('.zip'))continue;fs.copyFileSync(path.join(out,f),path.join(work,f));}
const zip=path.join(out,'RAMAVERSE-V5-AUTHORITY-RECOVERY-EVIDENCE.zip'); execFileSync('rm',['-f',zip]); execFileSync('zip',['-q','-X','-r',zip,'.'],{cwd:work}); execFileSync('unzip',['-tq',zip]); const sha=crypto.createHash('sha256').update(fs.readFileSync(zip)).digest('hex'); const entries=execFileSync('unzip',['-Z1',zip],{encoding:'utf8'}).trim().split('\n').length; fs.writeFileSync(path.join(out,'SHA256SUMS.txt'),`${sha}  RAMAVERSE-V5-AUTHORITY-RECOVERY-EVIDENCE.zip\n`); console.log(JSON.stringify({decision:map.decision,zip:zip,sha256:sha,entries},null,2));
