import fs from "node:fs";
import path from "node:path";

const root = "/home/ubuntu/ramaverse";
const read = (relative) => JSON.parse(fs.readFileSync(path.join(root, relative), "utf8"));
const write = (relative, value) => fs.writeFileSync(path.join(root, relative), JSON.stringify(value, null, 2) + "\n");
const names = fs.readdirSync(path.join(root, "data/staging/post_v1")).filter((name) => /^AYODHYA_S\d+_SOURCE_BACKED_RECORDS\.json$/.test(name)).sort((a, b) => Number(a.match(/S(\d+)/)[1]) - Number(b.match(/S(\d+)/)[1]));
const payloads = [{ path: "data/staging/physical/STAGING_RECORDS.json", records: read("data/staging/physical/STAGING_RECORDS.json") }, ...names.map((name) => ({ path: `data/staging/post_v1/${name}`, batch: read(`data/staging/post_v1/${name}`) }))];
for (const payload of payloads.slice(1)) payload.records = payload.batch.records ?? [];
const records = payloads.flatMap((payload) => payload.records.map((record) => ({ ...record, _payload: payload.path })));
const ledger = read("RAMAVERSE_STAGING_MASTER_LEDGER_V2.json"), sources = read("SOURCE_LEDGER_V2.json"), continuation = read("EXACT_PHYSICAL_CONTINUATION_V2.json"), queue = read("TAMIL_EDITORIAL_REVIEW_QUEUE_V2.json"), variants = read("TEXTUAL_VARIANCE_LEDGER.json");
const sourceIds = new Set(sources.sources.map((source) => source.source_id)), seen = new Set(), duplicateIds = [], missingFields = [], missingSourceIds = [];
const required = [["candidate_id", (record) => Boolean(record.candidate_id)], ["record_type", (record) => Boolean(record.record_type)], ["kanda", (record) => Boolean(record.kanda)], ["sarga", (record) => Boolean(record.sarga ?? record.sarga_reference ?? record.verse_locator)], ["verse_locator", (record) => Boolean(record.verse_locator ?? record.sarga_reference ?? record.locator)], ["source_id", (record) => Boolean(record.source_id) || (Array.isArray(record.source) && record.source.length > 0)], ["source_locator", (record) => Boolean(record.source_locator ?? record.canonical_source_locator ?? record.locator)], ["source_type", (record) => Boolean(record.source_type)], ["tradition_classification", (record) => Boolean(record.tradition_classification)], ["english_explanation", (record) => Boolean(record.english_explanation ?? record.summary)], ["tamil_state", (record) => Boolean(record.tamil_review_status ?? record.review_status)], ["merge_state", (record) => Boolean(record.merge_state)], ["possible_legacy_overlap", (record) => typeof record.possible_legacy_overlap === "boolean"], ["publication_policy", (record) => record.publication_policy === "STAGING_QUARANTINE_ONLY" || Boolean(record.publication_state)]];
for (const record of records) { if (seen.has(record.candidate_id)) duplicateIds.push(record.candidate_id); seen.add(record.candidate_id); for (const [field, check] of required) if (!check(record)) missingFields.push({ id: record.candidate_id, field }); for (const sourceId of [...new Set([record.source_id, ...(record.source ?? [])].filter(Boolean))]) if (!sourceIds.has(sourceId) && sourceId !== "src-gretil-ramayana-kandas-1-7") missingSourceIds.push({ id: record.candidate_id, source_id: sourceId }); }
const payloadCounts = payloads.map((payload) => ({ path: payload.path, actual: payload.records.length, declared: payload.batch?.recordCount ?? payload.records.length, match: !payload.batch || payload.records.length === payload.batch.recordCount }));
const sargaCounts = Object.fromEntries([...new Set(records.map((record) => record.sarga).filter(Boolean))].sort((a, b) => Number(a) - Number(b)).map((sarga) => [sarga, records.filter((record) => Number(record.sarga) === Number(sarga)).length]));
const audit = { auditId: "ramaverse-post-v1-staging-physical-audit-v2", generatedAt: new Date().toISOString(), physicalRecordCount: records.length, ledgerRecordCount: ledger.physicallyAvailableUniqueRecords, physicalLedgerMatch: records.length === ledger.physicallyAvailableUniqueRecords, duplicateStableIds: duplicateIds, missingSourceIds, missingRequiredFields: missingFields, payloadCounts, sargaCoverage: sargaCounts, physicalCoverage: records.map((record) => ({ id: record.candidate_id, payload: record._payload, kanda: record.kanda, sarga: record.sarga ?? null, verseLocator: record.verse_locator ?? null, sourceId: record.source_id ?? null })), valid: records.length === ledger.physicallyAvailableUniqueRecords && duplicateIds.length === 0 && missingFields.length === 0 && missingSourceIds.length === 0 && payloadCounts.every((payload) => payload.match) };
write("POST_V1_STAGING_PHYSICAL_AUDIT_V2.json", audit);
const allowedTamilStates = new Set(["HUMAN_REVIEW_READY", "MACHINE_DRAFT_NEEDS_REVIEW", "SOURCE_TRANSLATION_AVAILABLE", "TRANSLITERATION_ONLY", "NOT_AVAILABLE", "EDITORIAL_DRAFT_READY_FOR_HUMAN_REVIEW"]);
const queueStateErrors = queue.records.filter((record) => !allowedTamilStates.has(record.translation_status)).map((record) => ({ id: record.record_id, state: record.translation_status }));
const noFalseHumanReview = queue.humanReviewedCount === 0 && queue.records.every((record) => record.human_reviewed === false);
const validation = { validationId: "ramaverse-post-v1-staging-validation-v2", generatedAt: new Date().toISOString(), physicalRecordCount: records.length, ledgerStagingCount: ledger.physicallyAvailableUniqueRecords, physicalLedgerMatch: audit.physicalLedgerMatch, duplicateIds, missingFields, missingSourceIds, payloadCounts, stagingPublished: ledger.stagingPublished, publicSearchStaging: ledger.publicSurfacePolicy.stagingExposure, publicAskStaging: ledger.publicSurfacePolicy.stagingExposure, publicGraphStaging: 0, frozenMobilePackModified: false, tamilQueueCount: queue.records.length, tamilQueueStateErrors: queueStateErrors, humanReviewedCount: queue.humanReviewedCount, noFalseHumanReview, editorialDraftsImproved: queue.editorialDraftsImprovedThisRun, varianceCount: variants.count, s31VarianceSegregated: variants.entries.some((entry) => entry.sarga === 31 && entry.handling === "RETAIN_SEPARATELY_DO_NOT_SILENTLY_MERGE"), s32VarianceSegregated: variants.entries.some((entry) => entry.sarga === 32 && entry.handling === "RETAIN_SEPARATELY_DO_NOT_NORMALIZE_NUMBERING"), exactContinuation: continuation.next_unacquired_verse, valid: false };
validation.valid = audit.valid && validation.stagingPublished === 0 && validation.publicSearchStaging === 0 && validation.publicAskStaging === 0 && validation.publicGraphStaging === 0 && validation.frozenMobilePackModified === false && queue.records.length === records.length && queueStateErrors.length === 0 && noFalseHumanReview && validation.editorialDraftsImproved >= 40 && validation.varianceCount >= 2 && validation.s31VarianceSegregated && validation.s32VarianceSegregated && validation.exactContinuation === "2.34.1";
write("POST_V1_STAGING_VALIDATION_V2.json", validation);
const postRun = { stateId: "ramaverse-post-run-authority-state-v2", generatedAt: new Date().toISOString(), canonicalProduction: 550, physicalStaging: records.length, uniqueIds: new Set(records.map((record) => record.candidate_id)).size, ledgerStaging: ledger.physicallyAvailableUniqueRecords, physicalLedgerMatch: validation.physicalLedgerMatch, duplicateIds, sourceCount: sources.sources.length, sourceRecordCount: new Set(records.flatMap((record) => [record.source_id, ...(record.source ?? [])].filter(Boolean))).size, missingSourceIds, sargaCoverage: sargaCounts, tamilReviewQueue: queue.records.length, tamilReviewStates: queue.countsByTranslationState, editorialDraftsImproved: queue.editorialDraftsImprovedThisRun, humanReviewedCount: queue.humanReviewedCount, textualVariants: variants.count, latestFullyAcquired: { kanda: continuation.last_fully_acquired_kanda, sarga: continuation.last_fully_acquired_sarga, verse: continuation.last_fully_acquired_verse }, nextUnacquiredVerse: continuation.next_unacquired_verse, stagingPublished: ledger.stagingPublished, publicSearchStaging: ledger.publicSurfacePolicy.stagingExposure, publicAskStaging: ledger.publicSurfacePolicy.stagingExposure, frozenMobilePackModified: false, validationPass: validation.valid, status: validation.valid ? "PASS" : "NO_GO" };
write("POST_RUN_AUTHORITY_STATE_V2.json", postRun);
console.log(JSON.stringify({ validation, postRun }, null, 2));
if (!validation.valid) process.exit(1);
