import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

const root = "/home/ubuntu/ramaverse";
const read = (relative) => JSON.parse(fs.readFileSync(path.join(root, relative), "utf8"));
const write = (relative, value) => fs.writeFileSync(path.join(root, relative), JSON.stringify(value, null, 2) + "\n");
const payloadNames = fs.readdirSync(path.join(root, "data/staging/post_v1")).filter((name) => /^AYODHYA_S\d+_SOURCE_BACKED_RECORDS\.json$/.test(name)).sort((a, b) => Number(a.match(/S(\d+)/)[1]) - Number(b.match(/S(\d+)/)[1]));
const payloads = [{ path: "data/staging/physical/STAGING_RECORDS.json", records: read("data/staging/physical/STAGING_RECORDS.json") }, ...payloadNames.map((name) => ({ path: `data/staging/post_v1/${name}`, batch: read(`data/staging/post_v1/${name}`) }))];
for (const payload of payloads.slice(1)) payload.records = payload.batch.records ?? [];
const records = payloads.flatMap((payload) => payload.records.map((record) => ({ ...record, _payload: payload.path })));
const ledger = read("RAMAVERSE_STAGING_MASTER_LEDGER_VNEXT.json");
const sourceLedger = read("SOURCE_LEDGER_VNEXT.json");
const continuation = read("EXACT_PHYSICAL_CONTINUATION_VNEXT.json");
const tamilQueue = read("TAMIL_EDITORIAL_REVIEW_QUEUE_VNEXT.json");
const knownSources = new Set(sourceLedger.sources.map((source) => source.source_id));
const seen = new Set(), duplicateIds = [], missingFields = [], missingSourceIds = [];
const required = [
  ["candidate_id", (record) => Boolean(record.candidate_id)], ["record_type", (record) => Boolean(record.record_type)], ["kanda", (record) => Boolean(record.kanda)], ["sarga_or_section", (record) => Boolean(record.sarga ?? record.sarga_reference ?? record.verse_locator)], ["verse_locator", (record) => Boolean(record.verse_locator ?? record.sarga_reference ?? record.locator)], ["source_id", (record) => Boolean(record.source_id) || (Array.isArray(record.source) && record.source.length > 0)], ["source_locator", (record) => Boolean(record.source_locator ?? record.canonical_source_locator ?? record.locator)], ["source_type", (record) => Boolean(record.source_type)], ["tradition_classification", (record) => Boolean(record.tradition_classification)], ["confidence", (record) => Boolean(record.confidence)], ["review_state", (record) => Boolean(record.tamil_review_status ?? record.review_status)], ["merge_state", (record) => Boolean(record.merge_state)], ["possible_legacy_overlap", (record) => typeof record.possible_legacy_overlap === "boolean"]
];
for (const record of records) {
  if (seen.has(record.candidate_id)) duplicateIds.push(record.candidate_id);
  seen.add(record.candidate_id);
  for (const [field, predicate] of required) if (!predicate(record)) missingFields.push({ id: record.candidate_id, field });
  for (const sourceId of [...new Set([record.source_id, ...(record.source ?? [])].filter(Boolean))]) if (!knownSources.has(sourceId) && sourceId !== "src-gretil-ramayana-kandas-1-7") missingSourceIds.push({ id: record.candidate_id, source_id: sourceId });
}
const actualPayloadCounts = payloads.map((payload) => ({ path: payload.path, actual: payload.records.length, declared: payload.batch?.recordCount ?? payload.records.length, match: !payload.batch || payload.records.length === payload.batch.recordCount }));
const sectionCount = (sarga) => records.filter((record) => Number(record.sarga) === sarga && record.record_type === "VERSE_SECTION").length;
const scopeS30 = read("S30_SOURCE_SCOPE_EVIDENCE.json"), scopeS31 = read("S31_SOURCE_SCOPE_EVIDENCE.json");
const physicalCoverage = records.map((record) => ({ id: record.candidate_id, payload: record._payload, kanda: record.kanda, sarga: record.sarga ?? record.sarga_reference ?? null, verseLocator: record.verse_locator ?? record.sarga_reference ?? null, sourceIds: [...new Set([record.source_id, ...(record.source ?? [])].filter(Boolean))], sourceLocator: record.source_locator ?? record.canonical_source_locator ?? null }));
const audit = { auditId: "ramaverse-post-v1-staging-physical-audit-vnext", generatedAt: new Date().toISOString(), physicalRecordCount: records.length, ledgerRecordCount: ledger.physicallyAvailableUniqueRecords, physicalLedgerMatch: records.length === ledger.physicallyAvailableUniqueRecords, duplicateStableIds: duplicateIds, missingSourceIds, missingRequiredFields: missingFields, physicalCoverage, sargaCoverage: Object.fromEntries([...new Set(records.map((record) => record.sarga).filter(Boolean))].sort((a, b) => Number(a) - Number(b)).map((sarga) => [sarga, records.filter((record) => Number(record.sarga) === Number(sarga)).length])), payloadCounts: actualPayloadCounts, valid: records.length === ledger.physicallyAvailableUniqueRecords && duplicateIds.length === 0 && missingFields.length === 0 && missingSourceIds.length === 0 && actualPayloadCounts.every((payload) => payload.match) };
write("POST_V1_STAGING_PHYSICAL_AUDIT_VNEXT.json", audit);
const validation = { validationId: "ramaverse-post-v1-staging-validation-vnext", generatedAt: new Date().toISOString(), physicalRecordCount: records.length, ledgerStagingCount: ledger.physicallyAvailableUniqueRecords, physicalLedgerMatch: audit.physicalLedgerMatch, duplicateIds, missingFields, missingSourceIds, payloadCounts: actualPayloadCounts, stagingPublished: ledger.stagingPublished, publicSearchStaging: ledger.publicSurfacePolicy.stagingExposure, publicAskStaging: ledger.publicSurfacePolicy.stagingExposure, publicGraphStaging: 0, frozenMobilePackModified: false, s30SourceScopeVerified: scopeS30.primarySource.verseRange === "2.30.1–2.30.47", s31SourceScopeVerified: scopeS31.primarySource.verseRange === "2.31.1–2.31.35", s31EditionVarianceRecorded: Boolean(scopeS31.knownEditionVariance), s30DramaticSafeguards: records.filter((record) => Number(record.sarga) === 30 && String(record.content_safety ?? "").includes("NARRATIVE_DRAMATIC_EXPRESSION")).every((record) => String(record.content_safety).includes("NOT_INSTRUCTIONAL")), s30HistoricalNormSafeguards: records.filter((record) => Number(record.sarga) === 30 && record.record_type === "HISTORICAL_TEXTUAL_NORM").every((record) => String(record.content_safety).includes("NOT_MODERN_PRESCRIPTIVE_GUIDANCE")), s31HistoricalNormSafeguards: records.filter((record) => Number(record.sarga) === 31 && record.record_type === "HISTORICAL_TEXTUAL_NORM").every((record) => String(record.content_safety).includes("NOT_MODERN_PRESCRIPTIVE_GUIDANCE")), valid: false };
validation.valid = audit.valid && validation.stagingPublished === 0 && validation.publicSearchStaging === 0 && validation.publicAskStaging === 0 && validation.publicGraphStaging === 0 && validation.frozenMobilePackModified === false && validation.s30SourceScopeVerified && validation.s31SourceScopeVerified && validation.s31EditionVarianceRecorded && validation.s30DramaticSafeguards && validation.s30HistoricalNormSafeguards && validation.s31HistoricalNormSafeguards;
write("POST_V1_STAGING_VALIDATION_VNEXT.json", validation);
const postRun = { stateId: "ramaverse-post-run-authority-state-vnext", generatedAt: new Date().toISOString(), canonicalProduction: 550, physicalStaging: records.length, uniqueIds: new Set(records.map((record) => record.candidate_id)).size, ledgerStaging: ledger.physicallyAvailableUniqueRecords, physicalLedgerMatch: validation.physicalLedgerMatch, duplicateIds, sourceCount: sourceLedger.sources.length, sourceRecordCount: new Set(records.flatMap((record) => [record.source_id, ...(record.source ?? [])].filter(Boolean))).size, missingSourceIds, sargaCoverage: audit.sargaCoverage, tamilReviewCount: tamilQueue.records.length, tamilReviewStates: tamilQueue.countsByTranslationState, latestFullyAcquired: { kanda: continuation.last_fully_acquired_kanda, sarga: continuation.last_fully_acquired_sarga, verse: continuation.last_fully_acquired_verse }, nextUnacquiredVerse: continuation.next_unacquired_verse, stagingPublished: ledger.stagingPublished, publicSearchStaging: ledger.publicSurfacePolicy.stagingExposure, publicAskStaging: ledger.publicSurfacePolicy.stagingExposure, frozenMobilePackModified: false, validationPass: validation.valid, status: validation.valid ? "PASS" : "NO_GO" };
write("POST_RUN_AUTHORITY_STATE.json", postRun);
console.log(JSON.stringify({ validation, postRun }, null, 2));
if (!validation.valid) process.exit(1);
