import { useState, type ReactNode } from "react";
import { Activity, Archive, ArrowUpRight, BookOpen, CheckCircle2, Database, FileCheck2, Flag, Gauge, Globe2, ImageOff, Languages, LockKeyhole, Map, RefreshCw, ShieldCheck, Smartphone, Sparkles, TriangleAlert, Wifi } from "lucide-react";
import { RamaNavbar } from "@/components/RamaNavbar";
import { RamaFooter } from "@/components/RamaFooter";
import { useAuth } from "@/_core/hooks/useAuth";
import { ownerHealth, corpus, contentCoverage, languages, media, parity, release, quality, OWNER_COMMAND_CENTER_EVIDENCE, OWNER_COMMAND_CENTER_GENERATED_AT, ownerActions } from "@/lib/ownerCommandCenterData";

type Row = readonly [string, ...string[]];
const iconMap = { Website: Activity, Mobile: Smartphone, Corpus: Database, PWA: Wifi, Search: Sparkles, Ask: ShieldCheck, Languages, "Play release": Archive };
function StatusPill({ status }: { status: string }) { const good = ["PASS", "COMPLETE", "FROZEN"].includes(status); const warn = ["PARTIAL", "REVIEW REQUIRED", "NOT TESTED", "BLOCKED", "MISSING", "PENDING"].includes(status); return <span className={`owner-status ${good ? "owner-status-good" : warn ? "owner-status-warn" : ""}`}>{status}</span>; }
function Section({ id, icon: Icon, title, eyebrow, children }: { id:string; icon: typeof Activity; title:string; eyebrow:string; children:ReactNode }) { return <section id={id} className="owner-section" aria-labelledby={`${id}-title`}><div className="owner-section-head"><div><p className="owner-eyebrow"><Icon className="h-3.5 w-3.5" aria-hidden="true" /> {eyebrow}</p><h2 id={`${id}-title`}>{title}</h2></div></div>{children}</section>; }
function Table({ rows, headers = ["Area", "Status", "Evidence"] }: { rows: readonly Row[]; headers?: readonly string[] }) { return <div className="owner-table-wrap"><table className="owner-table"><thead><tr>{headers.map(h => <th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row[0]}><th scope="row">{row[0]}</th>{row.slice(1).map((cell,index) => <td key={`${row[0]}-${index}`}>{index === 0 && headers.length === row.length && ["PASS","COMPLETE","PARTIAL","MISSING","REVIEW REQUIRED","NOT TESTED","FROZEN","BLOCKED","PENDING"].includes(cell) ? <StatusPill status={cell} /> : cell}</td>)}</tr>)}</tbody></table></div>; }

export default function OwnerCommandCenter() {
  const [filter, setFilter] = useState("all");
  const auth = useAuth();
  if (auth.loading) return <main className="min-h-screen bg-[#070b14] px-6 py-32 text-center text-[#d7b45a]">Preparing owner view…</main>;
  if (!auth.user || auth.user.role !== "admin") return <main className="min-h-screen bg-[#070b14] px-6 py-32 text-center text-[#f3e9d2]"><LockKeyhole className="mx-auto mb-5 h-8 w-8 text-[#d7b45a]" aria-hidden="true" /><h1 className="font-serif text-3xl">Owner access required</h1><p className="mx-auto mt-3 max-w-md text-sm text-[#f3e9d2]/60">This local command center is restricted to the authenticated RamaVerse owner/admin account. No action was performed.</p></main>;
  const filteredParity = filter === "all" ? parity : parity.filter(row => row[1] === filter || row[2] === filter);
  return <div className="owner-shell min-h-screen bg-[#070b14] text-[#f3e9d2]"><RamaNavbar /><main className="mx-auto max-w-[1500px] px-5 py-12 lg:px-8 lg:py-16"><header className="owner-hero"><div><p className="owner-eyebrow"><LockKeyhole className="h-3.5 w-3.5" aria-hidden="true" /> Private / local evidence view</p><h1>Owner Command Center</h1><p>One calm surface for the true state of RamaVerse. Every status below is an evidence label, not a promise.</p><p className="owner-generated">Evidence snapshot: {new Date(OWNER_COMMAND_CENTER_GENERATED_AT).toLocaleString()} · {OWNER_COMMAND_CENTER_EVIDENCE.length} source files referenced</p></div><div className="owner-hero-mark" aria-hidden="true"><Gauge /><span>RC</span></div></header>
  <Section id="health" icon={Activity} eyebrow="Project health" title="What is healthy, frozen, or waiting"><div className="owner-health-grid">{ownerHealth.map(item => { const Icon = iconMap[item.label as keyof typeof iconMap] ?? Activity; return <article className="owner-health-card" key={item.label}><div className="owner-card-icon"><Icon className="h-4 w-4" aria-hidden="true" /></div><div><h3>{item.label}</h3><StatusPill status={item.status} /><p>{item.detail}</p></div></article>; })}</div></Section>
  <Section id="corpus" icon={Database} eyebrow="Corpus authority" title="The active truth"><div className="owner-kpi-grid">{corpus.slice(0,6).map(([label,value,status]) => <div className="owner-kpi" key={label}><span>{label}</span><strong>{value}</strong><StatusPill status={status} /></div>)}</div><Table rows={corpus.slice(6)} headers={["Measure","Value","State"]} /></Section>
  <Section id="content" icon={BookOpen} eyebrow="Content coverage" title="What exists, what is partial"><Table rows={contentCoverage} headers={["Domain","Coverage","Evidence note"]} /></Section>
  <Section id="languages" icon={Languages} eyebrow="Languages" title="UI and content truth"><Table rows={languages} headers={["Language","UI coverage","Content coverage","Human-reviewed / keys"]} /></Section>
  <Section id="media" icon={ImageOff} eyebrow="Media / art" title="Visible gaps, without placeholder claims"><div className="owner-media-grid">{media.map(([label,status,detail]) => <article className={`owner-media-card ${status === "MISSING" ? "owner-media-missing" : ""}`} key={label}><ImageOff className="h-5 w-5 text-[#d7b45a]" aria-hidden="true" /><div><h3>{label}</h3><StatusPill status={status} /><p>{detail}</p></div></article>)}</div></Section>
  <Section id="parity" icon={Smartphone} eyebrow="Website ↔ Mobile" title="Exact feature matrix"><div className="owner-filter" role="group" aria-label="Filter parity matrix"><button className={filter === "all" ? "active" : ""} onClick={() => setFilter("all")}>All</button>{["COMPLETE","PARTIAL","REVIEW REQUIRED","MISSING"].map(value => <button key={value} className={filter === value ? "active" : ""} onClick={() => setFilter(value)}>{value}</button>)}</div><Table rows={filteredParity} headers={["Feature","Website","Android","Evidence note"]} /></Section>
  <Section id="release" icon={Flag} eyebrow="Release control" title="No hidden deployment state"><Table rows={release} headers={["Release field","Current evidence"]} /></Section>
  <Section id="quality" icon={FileCheck2} eyebrow="Data quality" title="Governance gates"><Table rows={quality} headers={["Gate","Value","State"]} /></Section>
  <Section id="actions" icon={TriangleAlert} eyebrow="Owner actions" title="Only real next steps"><div className="owner-actions">{ownerActions.map((action,index) => <div className="owner-action" key={action}><span>{String(index+1).padStart(2,"0")}</span><p>{action}</p></div>)}</div><p className="owner-no-actions"><RefreshCw className="h-4 w-4" aria-hidden="true" /> There are no fake buttons here. This view records actions for the owner; it does not execute deployment, Play, corpus promotion, or Mobile changes.</p></Section>
  <footer className="owner-footer"><p><ShieldCheck className="inline h-4 w-4 text-[#d7b45a]" aria-hidden="true" /> Evidence source list is preserved in the RC archive.</p><div className="flex flex-wrap gap-3">{OWNER_COMMAND_CENTER_EVIDENCE.slice(0,4).map(file => <span className="owner-source" key={file}>{file}</span>)}</div></footer></main><RamaFooter /></div>;
}
