import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

const root = "/home/ubuntu/ramaverse";
const read = (relative) => JSON.parse(fs.readFileSync(path.join(root, relative), "utf8"));
const write = (relative, value) => fs.writeFileSync(path.join(root, relative), JSON.stringify(value, null, 2) + "\n");
const hash = (relative) => crypto.createHash("sha256").update(fs.readFileSync(path.join(root, relative))).digest("hex");
const names = fs.readdirSync(path.join(root, "data/staging/post_v1")).filter((name) => /^AYODHYA_S\d+_SOURCE_BACKED_RECORDS\.json$/.test(name)).sort((a, b) => Number(a.match(/S(\d+)/)[1]) - Number(b.match(/S(\d+)/)[1]));
const payloads = [{ path: "data/staging/physical/STAGING_RECORDS.json", records: read("data/staging/physical/STAGING_RECORDS.json") }, ...names.map((name) => ({ path: `data/staging/post_v1/${name}`, batch: read(`data/staging/post_v1/${name}`) }))];
for (const payload of payloads.slice(1)) payload.records = payload.batch.records ?? [];
const records = payloads.flatMap((payload) => payload.records.map((record) => ({ ...record, _payload: payload.path })));
const ids = records.map((record) => record.candidate_id), duplicateIds = [...new Set(ids.filter((id, index) => ids.indexOf(id) !== index))].sort();
const s34 = read("data/staging/post_v1/AYODHYA_S34_SOURCE_BACKED_RECORDS.json"), s35 = read("data/staging/post_v1/AYODHYA_S35_SOURCE_BACKED_RECORDS.json");
if (s34.records.length !== s34.recordCount || s35.records.length !== s35.recordCount || duplicateIds.length) throw new Error("S34/S35 count or duplicate gate failed");
const priorSources = read("SOURCE_LEDGER_V2.json");
const newSources = [
  { source_id: "src-valmiki-ayodhya-s34-sanskritdocuments", title: "Valmiki Ramayana — Ayodhya Kanda — Sarga 34", repository: "SanskritDocuments.org", edition_or_recension: "Traditional digital Sanskrit rendition with English word-for-word translation", language: "Sanskrit with English translation", sourceType: "PRIMARY_TEXT_DIGITAL_RENDITION", kanda: "Ayodhya Kanda", sarga: 34, verse_range: "2.34.1–2.34.61", url: "https://sanskritdocuments.org/sites/valmikiramayan/ayodhya/sarga34/ayodhyaroman34.htm", accessedAt: "2026-08-19", rights_status: "External reference; staging stores only original structured paraphrases.", tradition: "Valmiki", confidence: "high", caveat: "Primary acquisition locator. A suspended third-party host was excluded from source evidence." },
  { source_id: "src-valmiki-ayodhya-s34-stotranidhi-crosscheck", title: "Ayodhya Kanda Sarga 34 — complete chapter cross-check", repository: "Stotra Nidhi", edition_or_recension: "Traditional digital IAST presentation", language: "Sanskrit (IAST)", sourceType: "PRIMARY_TEXT_DIGITAL_CROSSCHECK", kanda: "Ayodhya Kanda", sarga: 34, verse_range: "2.34.1–2.34.61", url: "https://stotranidhi.com/en/ayodhya-kanda-sarga-34-in-english/", accessedAt: "2026-08-19", rights_status: "External reference; no continuous source text reproduced.", tradition: "Valmiki", confidence: "medium", caveat: "Confirms the 61-verse chapter scope." },
  { source_id: "src-valmiki-ayodhya-s35-stotranidhi", title: "Valmiki Ramayana — Ayodhya Kanda — Sarga 35", repository: "Stotra Nidhi", edition_or_recension: "Traditional digital IAST presentation", language: "Sanskrit (IAST)", sourceType: "PRIMARY_TEXT_DIGITAL_RENDITION", kanda: "Ayodhya Kanda", sarga: 35, verse_range: "2.35.1–2.35.35", url: "https://stotranidhi.com/en/ayodhya-kanda-sarga-35-in-english/", accessedAt: "2026-08-19", rights_status: "External reference; staging stores only original structured paraphrases.", tradition: "Valmiki", confidence: "high", caveat: "Primary acquisition locator. Host availability was independently checked; suspended mirror not used." },
  { source_id: "src-valmiki-ayodhya-s35-vedapath-v21-crosscheck", title: "Valmiki Ramayana 2.35.21 — verse cross-check", repository: "Vedapath", edition_or_recension: "Digital verse presentation", language: "Sanskrit with English interface", sourceType: "PRIMARY_TEXT_DIGITAL_CROSSCHECK", kanda: "Ayodhya Kanda", sarga: 35, verse_range: "2.35.21", url: "https://vedapath.app/en/ramayana/ayodhya-kanda/35/21", accessedAt: "2026-08-19", rights_status: "External reference; no continuous source text reproduced.", tradition: "Valmiki", confidence: "medium", caveat: "Confirms the embedded backstory locator only; derived ethical FAQs are not used as source evidence." }
];
const known = new Set(priorSources.sources.map((source) => source.source_id));
const sourceLedger = { ...priorSources, ledgerId: "ramaverse-master-source-ledger-v3", generatedAt: new Date().toISOString(), sources: [...priorSources.sources, ...newSources.filter((source) => !known.has(source.source_id))] };
write("SOURCE_LEDGER_V3.json", sourceLedger);
const ledger = { ledgerId: "ramaverse-website-staging-master-ledger-v3", generatedAt: new Date().toISOString(), mode: "physical-records-only", historicalCanonicalBaseline: 550, stagingPublished: 0, physicallyAvailableUniqueRecords: records.length, candidateRecordsNotCountedAsPhysicalStaging: 7, recordPayloads: payloads.map((payload) => ({ path: payload.path, records: payload.records.length })), duplicates: { candidateIds: duplicateIds, count: duplicateIds.length }, latestVerifiedCoverage: { kanda: "Ayodhya Kanda", sarga: 35, verseRange: "2.35.1–2.35.35", status: "PHYSICAL_STAGING_SOURCE_BACKED", editionVariance: "No numbering variance newly identified; source host status difference is documented, not treated as a recension variance." }, nextAcquisitionPoint: { kanda: "Ayodhya Kanda", sarga: 36, verseRange: "2.36.1 onward", status: "SOURCE_PROCUREMENT_PENDING" }, publicSurfacePolicy: { search: "CANONICAL_ONLY", ask: "CANONICAL_ONLY", stagingExposure: 0 } };
write("RAMAVERSE_STAGING_MASTER_LEDGER_V3.json", ledger);
write("EXACT_PHYSICAL_CONTINUATION_V3.json", { ledgerId: "ramaverse-exact-physical-continuation-v3", generatedAt: new Date().toISOString(), historicalCanonicalBaseline: 550, physicalStagingCount: records.length, last_fully_acquired_kanda: "Ayodhya Kanda", last_fully_acquired_sarga: 35, last_fully_acquired_verse: "2.35.35", next_unacquired_verse: "2.36.1", source_id: "src-valmiki-ayodhya-s35-stotranidhi", source_locator: "Stotra Nidhi, Ayodhya Kanda, Sarga 35, verses 2.35.1–2.35.35", supporting_record_ids: ["stg-postv1-ayodhyakanda-s35-sarga-001", "stg-postv1-ayodhyakanda-s35-source-001"], duplicate_prevention: "Next acquisition begins only at Sarga 36, verse 2.36.1; existing 21–35 physical staging is retained unchanged except metadata normalization." });
write("S34_SOURCE_SCOPE_EVIDENCE.json", { evidenceId: "ramaverse-s34-source-scope-v1", generatedAt: new Date().toISOString(), primarySource: { sourceId: "src-valmiki-ayodhya-s34-sanskritdocuments", repository: "SanskritDocuments.org", work: "Valmiki Ramayana", kanda: "Ayodhya Kanda", sarga: 34, verseRange: "2.34.1–2.34.61", edition: "Traditional digital rendition; not a critical edition", language: "Sanskrit with English translation", url: "https://sanskritdocuments.org/sites/valmikiramayan/ayodhya/sarga34/ayodhyaroman34.htm", accessDate: "2026-08-19", rightsStatus: "External reference" }, crossChecks: [{ sourceId: "src-valmiki-ayodhya-s34-stotranidhi-crosscheck", chapterScope: "2.34.1–2.34.61" }], excludedSources: [{ url: "https://www.valmikiramayan.net/ayodhya/sarga34/ayodhya_34_frame.htm", reason: "Account suspended; not evidence." }], result: "PASS" });
write("S35_SOURCE_SCOPE_EVIDENCE.json", { evidenceId: "ramaverse-s35-source-scope-v1", generatedAt: new Date().toISOString(), primarySource: { sourceId: "src-valmiki-ayodhya-s35-stotranidhi", repository: "Stotra Nidhi", work: "Valmiki Ramayana", kanda: "Ayodhya Kanda", sarga: 35, verseRange: "2.35.1–2.35.35", edition: "Traditional digital IAST presentation; not a critical edition", language: "Sanskrit (IAST)", url: "https://stotranidhi.com/en/ayodhya-kanda-sarga-35-in-english/", accessDate: "2026-08-19", rightsStatus: "External reference" }, crossChecks: [{ sourceId: "src-valmiki-ayodhya-s35-vedapath-v21-crosscheck", verse: "2.35.21" }], excludedSources: [{ url: "https://www.valmikiramayan.net/utf8/ayodhya/sarga35/ayodhyaitrans35.htm", reason: "Account suspended; not evidence." }], result: "PASS" });
const variance = read("TEXTUAL_VARIANCE_LEDGER.json"); write("TEXTUAL_VARIANCE_LEDGER_V2.json", { ...variance, ledgerId: "ramaverse-textual-variance-ledger-v2", generatedAt: new Date().toISOString(), v3RunResult: "No new recension or numbering variance added for Sargas 34–35; existing two entries preserved." });
const stateFor = (record) => { const raw = String(record.tamil_review_status ?? "").toUpperCase(); return raw === "EDITORIAL_DRAFT_READY_FOR_HUMAN_REVIEW" ? raw : raw.includes("SOURCE_TAMIL") ? "SOURCE_TRANSLATION_AVAILABLE" : raw.includes("TRANSLITERATION") ? "TRANSLITERATION_ONLY" : raw.includes("NOT_AVAILABLE") ? "NOT_AVAILABLE" : "MACHINE_DRAFT_NEEDS_REVIEW"; };
const priority = (record) => ({ DIALOGUE: "P1", DHARMA_LESSON: "P1", EVENT: "P2", SARGA: "P2", HISTORICAL_TEXTUAL_NORM: "P2", THEME: "P2", RELATIONSHIP: "P3", CHARACTER_REFERENCE: "P3", JOURNEY: "P3", PLACE: "P3", VERSE_SECTION: "P3", SOURCE_REFERENCE: "P4" }[record.record_type] ?? "P4");
const queueRecords = records.map((record) => ({ record_id: record.candidate_id, record_type: record.record_type, source_locator: record.source_locator ?? null, current_tamil_text: record.tamil_draft ?? record.tamil_explanation ?? null, translation_status: stateFor(record), priority: priority(record), human_reviewed: false, editorial_work: stateFor(record) === "EDITORIAL_DRAFT_READY_FOR_HUMAN_REVIEW" ? "Source-faithful editorial Tamil draft checked for syntax, punctuation, mixed-script spacing, safeguards, and named-entity consistency; human review remains required." : "Existing Tamil draft retained for human editorial refinement; no human-review claim is made.", merge_state: record.merge_state ?? "awaiting_v1_4_0_reconciliation", publication_state: "STAGING_QUARANTINE_ONLY" })).sort((a, b) => a.priority.localeCompare(b.priority) || a.record_id.localeCompare(b.record_id));
const countBy = (items, key) => items.reduce((out, item) => ({ ...out, [item[key]]: (out[item[key]] ?? 0) + 1 }), {});
write("TAMIL_EDITORIAL_REVIEW_QUEUE_V3.json", { queueId: "ramaverse-tamil-editorial-review-queue-v3", generatedAt: new Date().toISOString(), scope: "All physical staging only; none are human reviewed or public.", records: queueRecords, countsByTranslationState: countBy(queueRecords, "translation_status"), countsByPriority: countBy(queueRecords, "priority"), editorialDraftsImprovedThisRun: [...s34.records, ...s35.records].filter((record) => stateFor(record) === "EDITORIAL_DRAFT_READY_FOR_HUMAN_REVIEW").length, humanReviewedCount: 0 });
write("V1_5_RECONCILIATION_PREVIEW_V3.json", { previewId: "ramaverse-v1.5-reconciliation-preview-v3", generatedAt: new Date().toISOString(), status: "EDITORIAL_PREVIEW_ONLY_NOT_PRODUCTION_READY", historicalCanonicalBaseline: 550, stagingPublished: 0, physicalStagingRecords: records.length, counts: { NEW_CANONICAL_CANDIDATE: records.filter((record) => record.reconciliation_classification === "NEW_CANONICAL_CANDIDATE").length, ENRICH_EXISTING: 0, DUPLICATE: duplicateIds.length, VARIANT: variance.entries.length, CONFLICT: 0, SOURCE_REVIEW: records.filter((record) => record.reconciliation_classification === "SOURCE_REVIEW").length, TAMIL_REVIEW: queueRecords.length, REJECTED: 0 }, guardrails: ["No staging record is added to the frozen 550 baseline.", "No staging record is exposed through public Search, Ask, graph, or the frozen v1.4.0 mobile pack.", "Textual variants remain separately pending editorial reconciliation."] });
write("RAMAVERSE-CANONICAL-MOBILE-PACK-v1.5.0-CANDIDATE-METADATA-V3.json", { metadataId: "ramaverse-v1.5.0-candidate-metadata-v3", generatedAt: new Date().toISOString(), status: "METADATA_ONLY_NOT_A_MOBILE_PACK", approvedMobilePack: "RAMAVERSE-CANONICAL-MOBILE-PACK-v1.4.0-FINAL-v2.zip", approvedPackModified: false, stagingRecordCount: records.length, newThisRunCandidateIds: [...s34.records, ...s35.records].map((record) => record.candidate_id), eligibility: "Requires authoritative v1.5 reconciliation, source review, and human Tamil editorial approval before any mobile pack can be generated.", stagingPublished: 0, publicExposure: 0 });
const relationEdges = records.filter((record) => record.record_type === "RELATIONSHIP" && record.subject && record.object).map((record) => ({ from: record.subject, to: record.object, relation: record.relation, evidence_id: record.candidate_id, source_id: record.source_id, verse_locator: record.verse_locator })), dialogueEdges = records.filter((record) => record.record_type === "DIALOGUE").map((record) => ({ from: record.speaker, to: record.listener, relation: "SPEAKS_TO", evidence_id: record.candidate_id, source_id: record.source_id, verse_locator: record.verse_locator }));
write("POST_V1_STAGING_KNOWLEDGE_GRAPH_V3.json", { graphId: "ramaverse-post-v1-staging-knowledge-graph-v3", generatedAt: new Date().toISOString(), visibility: "EDITORIAL_ONLY_STAGING", publicGraphExposure: 0, nodes: records.map((record) => ({ id: record.candidate_id, type: record.record_type, source_id: record.source_id ?? null, staging_state: "QUARANTINED" })), edges: [...relationEdges, ...dialogueEdges], safeguards: "Public knowledge graph remains canonical-only." });
write("POST_V1_EDITORIAL_INDEX_V3.json", { indexId: "ramaverse-post-v1-editorial-index-v3", generatedAt: new Date().toISOString(), visibility: "EDITORIAL_ONLY_STAGING", canonicalBaseline: 550, stagingRecords: records.length, publicSearchEntries: 0, publicAskEntries: 0, byRecordType: countBy(records, "record_type"), bySarga: countBy(records.filter((record) => record.sarga), "sarga") });
write("RELATIONAL_DIALOGUE_EVIDENCE_V3.json", { evidenceId: "ramaverse-relational-dialogue-evidence-v3", generatedAt: new Date().toISOString(), visibility: "EDITORIAL_ONLY_STAGING", s34: { dialogues: s34.records.filter((record) => record.record_type === "DIALOGUE").map((record) => record.candidate_id), relationships: s34.records.filter((record) => record.record_type === "RELATIONSHIP").map((record) => record.candidate_id), dharma: s34.records.filter((record) => record.record_type === "DHARMA_LESSON").map((record) => record.candidate_id) }, s35: { dialogues: s35.records.filter((record) => record.record_type === "DIALOGUE").map((record) => record.candidate_id), relationships: s35.records.filter((record) => record.record_type === "RELATIONSHIP").map((record) => record.candidate_id), sourceReview: s35.records.filter((record) => record.reconciliation_classification === "SOURCE_REVIEW").map((record) => record.candidate_id) }, boundary: "All evidence is source-bound narrative staging, not public advice, approved lineage, or canonical claims." });
const currentEvents = [...s34.records, ...s35.records].filter((record) => record.record_type === "EVENT");
write("RAMA_LIFE_EVENT_DERIVATION_V3.json", { evidenceId: "ramaverse-rama-life-event-derivation-v3", generatedAt: new Date().toISOString(), visibility: "EDITORIAL_ONLY_STAGING", rule: "Rama Life derives only from EVENT records; no independent biography is created.", events: currentEvents.map((record, index) => ({ sequence: index + 1, event_id: record.candidate_id, title: record.event_title, participants: record.participants, kanda: record.kanda, sarga: record.sarga, verse_locator: record.verse_locator, source_id: record.source_id, related_dialogues: [...s34.records, ...s35.records].filter((dialogue) => dialogue.related_event_id === record.candidate_id).map((dialogue) => dialogue.candidate_id) })) });
const state = read("RAMAVERSE_PROJECT_STATE.json");
write("RAMAVERSE_PROJECT_STATE.json", { ...state, RV_01_staging_count: records.length, staging_published: 0, staging_files: [...new Set([...state.staging_files, "data/staging/post_v1/AYODHYA_S34_SOURCE_BACKED_RECORDS.json", "data/staging/post_v1/AYODHYA_S35_SOURCE_BACKED_RECORDS.json"])], stable_id_registries: [...new Set([...state.stable_id_registries, "RAMAVERSE_STAGING_MASTER_LEDGER_V3.json", "TEXTUAL_VARIANCE_LEDGER_V2.json"])], RV_01_continuation: "Ayodhya Kanda Sarga 36, verse 2.36.1 onward", source_clusters: [...new Set([...state.source_clusters, "Valmiki Ramayana / Ayodhya Kanda / Sargas 34–35 physical source-backed staging"])], latest_batch_ids: ["AYODHYA_S34_SOURCE_BACKED_RECORDS", "AYODHYA_S35_SOURCE_BACKED_RECORDS", "TAMIL_EDITORIAL_REVIEW_QUEUE_V3", "TEXTUAL_VARIANCE_LEDGER_V2"], task_output_map: { ...state.task_output_map, physical_ledger: "RAMAVERSE_STAGING_MASTER_LEDGER_V3.json", continuation: "EXACT_PHYSICAL_CONTINUATION_V3.json", source_ledger: "SOURCE_LEDGER_V3.json", tamil_queue: "TAMIL_EDITORIAL_REVIEW_QUEUE_V3.json", variance_ledger: "TEXTUAL_VARIANCE_LEDGER_V2.json" }, SHA256: { ...state.SHA256, s34_staging_payload: hash("data/staging/post_v1/AYODHYA_S34_SOURCE_BACKED_RECORDS.json"), s35_staging_payload: hash("data/staging/post_v1/AYODHYA_S35_SOURCE_BACKED_RECORDS.json"), staging_ledger_v3: hash("RAMAVERSE_STAGING_MASTER_LEDGER_V3.json") }, exact_next_point: "Ayodhya Kanda / Sarga 36 / verse 2.36.1", updated_at: new Date().toISOString() });
console.log(JSON.stringify({ physicalStaging: records.length, s34Records: s34.records.length, s35Records: s35.records.length, sources: sourceLedger.sources.length, editorialDraftsImproved: [...s34.records, ...s35.records].filter((record) => stateFor(record) === "EDITORIAL_DRAFT_READY_FOR_HUMAN_REVIEW").length, variants: variance.entries.length, duplicateIds, status: "PASS" }, null, 2));
