import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
const root = "/home/ubuntu/ramaverse";
const src = path.join(root, "data", "p0_conflict_resolution_vnext");
const out = path.join(root, "release_evidence", "p0_conflict_resolution");
mkdirSync(out, { recursive: true });
const required = ["RAMAVERSE_P0_CONFLICT_ROOT_CAUSE_LEDGER.json", "RAMAVERSE_P0_SOURCE_EVIDENCE_MAP.json", "RAMAVERSE_P0_RESOLUTION_LEDGER.json", "RAMAVERSE_P0_RESOLUTION_PATCHES.json", "RAMAVERSE_P0_VARIANT_LEDGER.json", "RAMAVERSE_P0_ENTITY_ALIAS_CROSSWALKS.json", "RAMAVERSE_FINAL_HUMAN_EDITOR_QUEUE.json", "RAMAVERSE_P0_CANDIDATE_LEDGER.json", "RAMAVERSE_P0_VALIDATION.json", "RAMAVERSE_P0_SUMMARY.md"];
const missing = required.filter((file) => !existsSync(path.join(src, file)));
if (missing.length) throw new Error(`Missing required artifacts: ${missing.join(", ")}`);
const validation = JSON.parse(readFileSync(path.join(src, "RAMAVERSE_P0_VALIDATION.json"), "utf8"));
if (validation.status !== "PASS") throw new Error("P0 validation gate is not PASS");
const target = path.join(out, "RAMAVERSE-P0-CONFLICT-MAX-RESOLUTION-MASTER.zip");
execFileSync("rm", ["-f", target]);
const inputs = ["data/p0_conflict_resolution_vnext", "PROJECT_STATE.json", "CORPUS_STATE.json", "CONTINUATION.md", "SOURCE_MANIFEST.json"];
execFileSync("zip", ["-qr", target, ...inputs, "-x", "*.zip", "-x", "node_modules/*", "-x", "dist/*", "-x", ".git/*"], { cwd: root, stdio: "ignore" });
execFileSync("unzip", ["-tq", target], { stdio: "ignore" });
const listing = execFileSync("unzip", ["-Z1", target], { encoding: "utf8", maxBuffer: 32 * 1024 * 1024 });
const entries = listing.split("\n").filter(Boolean);
const sha256 = createHash("sha256").update(readFileSync(target)).digest("hex");
const manifest = { generatedAt: new Date().toISOString(), file: path.basename(target), bytes: statSync(target).size, entries: entries.length, sha256, integrity: "PASS", requiredFilesPresent: required.every((file) => entries.includes(`data/p0_conflict_resolution_vnext/${file}`)), canonicalBaseline: 550, canonicalChanged: 0, stagingPublished: 0, mobileModified: false, productionDeployed: false, status: "PASS" };
if (!manifest.requiredFilesPresent) throw new Error("Required P0 artifact missing from archive");
writeFileSync(path.join(out, "MANIFEST.json"), JSON.stringify(manifest, null, 2) + "\n");
writeFileSync(path.join(out, "SHA256SUMS.txt"), `${sha256}  ${path.basename(target)}\n`);
console.log(JSON.stringify(manifest, null, 2));
