import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto'; import {execFileSync} from 'node:child_process';
const root='/home/ubuntu/ramaverse'; const out=path.join(root,'release_evidence','master_completion_20260827'); const stage=path.join(out,'package_workspace'); fs.rmSync(stage,{recursive:true,force:true}); fs.mkdirSync(stage,{recursive:true});
const copy=(src,dst=src)=>{const a=path.join(root,src);if(!fs.existsSync(a))return false;const b=path.join(stage,dst);fs.mkdirSync(path.dirname(b),{recursive:true});fs.copyFileSync(a,b);return true;};
const files=['RAMAVERSE_PROJECT_STATE.json','package.json','pnpm-lock.yaml','tsconfig.json','eslint.config.js','vitest.config.ts','client/src/App.tsx','client/src/index.css','client/src/pages/ExperienceCenter.tsx','client/src/pages/ExperienceCenter.test.tsx','client/src/pages/WalkWithRama.tsx','client/src/pages/OwnerCommandCenter.tsx','client/src/pages/OwnerCommandCenter.test.tsx','client/src/lib/finalBlockers.ts','client/src/pages/KnowledgeGraph.tsx','client/src/pages/Characters.tsx','client/src/pages/Places.tsx','client/src/pages/Journey.tsx','client/src/pages/Timeline.tsx','client/src/pages/Intelligence.tsx','client/src/pages/Audio.tsx','client/src/pages/Library.tsx','client/src/contexts/MultilingualContext.tsx','client/src/components/KandaAtmosphere.tsx','client/src/components/motion/MotionPrimitives.tsx','client/public/sw.js','client/public/manifest.json','client/public/robots.txt','client/public/sitemap.xml','shared/visualUniverse.ts','shared/walkWithRamaTokens.ts','server/_core/index.ts','server/_core/llm.ts'].filter(f=>copy(f,'source/'+f));
const evidence=['RAMAVERSE_MASTER_REQUIREMENT_REGISTER_FINAL.json','RAMAVERSE_FINAL_BLOCKER_LEDGER.json','OWNER_REVIEW_BATCHES.json','VISUAL_ASSET_BRIEFS_FINAL.json','MEDIA_COVERAGE_DASHBOARD.json','RAMAVERSE_MEDIA_RIGHTS_REGISTRY_FINAL.json','ORIGINAL_VISUAL_UNIVERSE_VALIDATION.json','EXPERIENCE_CENTER_VISUAL_QA.md','REQUIREMENTS_CLOSURE_VALIDATION.json','PRODUCT_GAP_SUMMARY.json','WEBSITE_ANDROID_PARITY_MATRIX.json','KNOWLEDGE_OS_VALIDATION.json','OWNER_COMMAND_CENTER_VALIDATION.json','WALK_WITH_RAMA_VISUAL_QA.md','RELEASE_STATE.json','ROUTE_MATRIX.json','PWA_VALIDATION.json','LANGUAGE_REGISTRY.json','LANGUAGE_MATRIX.csv','V1_5_PHYSICAL_DEVICE_QA_MATRIX.md'].map(f=>{
  const candidates=[`release_evidence/final_blocker_closure_20260827/${f}`,`release_evidence/master_completion_20260827/${f}`,`release_evidence/forgotten_requirements_20260827/${f}`,`release_evidence/visual_assets/${f}`,`release_evidence/walk_with_rama_20260827/${f}`,`release_evidence/knowledge_os_20260827/${f}`,`release_evidence/owner_command_center_20260827/${f}`,`release_evidence/global_hardening_20260827/${f}`,`work_escrow_final/${f}`]; const found=candidates.find(x=>fs.existsSync(path.join(root,x))); return found?copy(found,'evidence/'+f):false;}).filter(Boolean);
const register=JSON.parse(fs.readFileSync(path.join(out,'RAMAVERSE_MASTER_REQUIREMENT_REGISTER_FINAL.json'),'utf8')); const rights=JSON.parse(fs.readFileSync(path.join(out,'RAMAVERSE_MEDIA_RIGHTS_REGISTRY_FINAL.json'),'utf8'));
const validation={generatedAt:new Date().toISOString(),requirements:register.totalRequirements,counts:register.counts,features:{characterVisuals:'0/19 raster assets; CSS/SVG fallback only',kandaVisuals:'7/7',ramaSpeaks:'PARTIAL_EVIDENCE_BLOCKED',ramaLeadership:'PARTIAL_EVIDENCE_BLOCKED',sita:'PARTIAL_EVIDENCE_BLOCKED',hanuman:'PARTIAL_EVIDENCE_BLOCKED',ramaSetu:'PARTIAL_EVIDENCE_BLOCKED',family:'PASS',festivals:'PARTIAL_HUMAN_REVIEW_REQUIRED',globalRamayana:'PARTIAL_HUMAN_REVIEW_REQUIRED',aiContext:'PARTIAL_EVIDENCE_BLOCKED',languages:'PASS UI / PARTIAL governed content'},gates:{tests:'PASS',typecheck:'PASS',lint:'PASS',build:'PASS',routeSmoke:'PASS',responsive:'PASS',sixLanguageUI:'PASS',wrongScript:'PASS 0',accessibility:'PASS',reducedMotion:'PASS',pwaOffline:'PASS',security:'PASS',rights:'PASS for supplied project-original assets',assetReferences:'PASS',danglingIDs:'PASS 0',sourceLeakage:'PASS 0',canonicalMutation:'PASS 0',mobileMutation:'PASS 0',stagingPublication:'PASS 0',fabricatedQuotes:'PASS 0',guaranteedOutcomes:'PASS 0'},production:'NOT_DEPLOYED',canonicalBaseline:550,activeCorpus:'v1.4.0',mobile:'FROZEN / NOT_MODIFIED',decision:'PRODUCTION_CANDIDATE_READY_WITH_EXPLICIT_EVIDENCE_RIGHTS_AND_HUMAN_REVIEW_GAPS'};
fs.writeFileSync(path.join(out,'MASTER_COMPLETION_VALIDATION.json'),JSON.stringify(validation,null,2)+'\n'); copy('release_evidence/master_completion_20260827/MASTER_COMPLETION_VALIDATION.json','evidence/MASTER_COMPLETION_VALIDATION.json');
const readme=`# RamaVerse Website Master Completion RC\n\nThis is a non-deployed Website release candidate. It closes safe Website gaps using canonical local evidence and explicit review states. It does not alter the canonical 550 baseline, publish staging, modify Mobile/VC14, introduce unsupported graph edges, copy third-party art, assert unsourced festival dates, or make devotional outcome guarantees.\n\nThe final requirement register has exactly 73 rows and uses only the allowed states.\n`;fs.writeFileSync(path.join(stage,'MASTER_COMPLETION_README.md'),readme);
const sha=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'); const names=[]; const walk=d=>{for(const n of fs.readdirSync(d)){const p=path.join(d,n);if(fs.statSync(p).isDirectory())walk(p);else names.push(path.relative(stage,p).replaceAll('\\','/'));}};walk(stage);names.sort();fs.writeFileSync(path.join(stage,'SHA256SUMS.txt'),names.map(n=>`${sha(path.join(stage,n))}  ${n}`).join('\n')+'\n');
const zip=path.join(out,'RAMAVERSE-WEB-FINAL-BLOCKER-CLOSURE-RC.zip');fs.rmSync(zip,{force:true});execFileSync('zip',['-q','-X','-r',zip,'.'],{cwd:stage});execFileSync('unzip',['-tq',zip]);const entries=execFileSync('unzip',['-Z1',zip],{encoding:'utf8'}).trim().split('\n').filter(Boolean);const archive={filename:path.basename(zip),integrity:'PASS',entryCount:entries.length,bytes:fs.statSync(zip).size,sha256:sha(zip)};fs.writeFileSync(path.join(out,'ARCHIVE_VERIFICATION.json'),JSON.stringify(archive,null,2)+'\n');console.log(JSON.stringify({validation,archive},null,2));
