import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, statSync, existsSync, mkdirSync } from "node:fs";
import path from "node:path";
const root = "/home/ubuntu/ramaverse";
const dir = path.join(root, "data/v1_5_safe_enrichment_candidate");
const evidence = path.join(root, "release_evidence");
const out = path.join(evidence, "v1_5_safe_enrichment");
mkdirSync(out, { recursive: true });
const required = ["RAMAVERSE_CANONICAL_V1_5_ENRICHED_CANDIDATE.json", "SAFE_ENRICHMENT_APPLIED.json", "SAFE_ENRICHMENT_REJECTED.json", "CANDIDATE_PROVENANCE.json", "V1_5_PROJECTION_COMPARISON.json", "SEARCH_INDEX_V1_5_ENRICHED_CANDIDATE.json", "ASK_INDEX_V1_5_ENRICHED_CANDIDATE.json", "READER_MAPPINGS_V1_5_ENRICHED_CANDIDATE.json", "ENTITY_PROJECTIONS_V1_5_ENRICHED_CANDIDATE.json", "TIMELINE_PROJECTIONS_V1_5_ENRICHED_CANDIDATE.json", "CHARACTER_CONTEXT_V1_5_ENRICHED_CANDIDATE.json", "PLACE_CONTEXT_V1_5_ENRICHED_CANDIDATE.json"];
const missing = required.filter((file) => !existsSync(path.join(dir, file)));
if (missing.length) throw new Error(`Missing candidate files: ${missing.join(", ")}`);
const validationPath = path.join(evidence, "RAMAVERSE-WEB-v1.5-SAFE-ENRICHMENT-VALIDATION.json");
const validation = JSON.parse(readFileSync(validationPath, "utf8"));
const target = path.join(out, "RAMAVERSE-WEB-v1.5-SAFE-ENRICHMENT-CANDIDATE.zip");
execFileSync("rm", ["-f", target]);
execFileSync("zip", ["-qr", target, "data/v1_5_safe_enrichment_candidate", "release_evidence/RAMAVERSE-WEB-v1.5-SAFE-ENRICHMENT-VALIDATION.json", "PROJECT_STATE.json", "CORPUS_STATE.json", "SOURCE_MANIFEST.json", "CONTINUATION.md", "-x", "*.zip", "-x", "node_modules/*", "-x", "dist/*", "-x", ".git/*"], { cwd: root, stdio: "ignore" });
execFileSync("unzip", ["-tq", target], { stdio: "ignore" });
const listing = execFileSync("unzip", ["-Z1", target], { encoding: "utf8", maxBuffer: 32 * 1024 * 1024 });
const entries = listing.split("\n").filter(Boolean);
const sha256 = createHash("sha256").update(readFileSync(target)).digest("hex");
const manifest = { generated_at: new Date().toISOString(), file: path.basename(target), bytes: statSync(target).size, entries: entries.length, sha256, integrity: "PASS", required_files_present: required.every((file) => entries.includes(`data/v1_5_safe_enrichment_candidate/${file}`)), validation_present: entries.includes("release_evidence/RAMAVERSE-WEB-v1.5-SAFE-ENRICHMENT-VALIDATION.json"), baseline_canonical: 550, patches_input: 184, patches_applied: validation.patches_applied, patches_rejected: validation.patches_rejected, final_canonical: validation.final_canonical, staging_leakage: validation.staging_leakage, production_deployed: false, mobile_modified: false, decision: validation.decision };
writeFileSync(path.join(out, "MANIFEST.json"), JSON.stringify(manifest, null, 2) + "\n");
writeFileSync(path.join(out, "SHA256SUMS.txt"), `${sha256}  ${path.basename(target)}\n`);
console.log(JSON.stringify(manifest, null, 2));
