import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto'; import {execFileSync} from 'node:child_process';
const root='/home/ubuntu/ramaverse';const out=path.join(root,'release_evidence','master_product_gap_recovery_20260827');const stage=path.join(out,'package_workspace');fs.rmSync(stage,{recursive:true,force:true});fs.mkdirSync(stage,{recursive:true});
const summary=JSON.parse(fs.readFileSync(path.join(out,'PRODUCT_GAP_SUMMARY.json'),'utf8'));
const files=['RAMAVERSE_MASTER_REQUIREMENT_REGISTER.json','WEBSITE_MOBILE_PARITY_MATRIX.json','PRODUCT_GAP_SUMMARY.json','SHA256SUMS.txt'];
const evidence=['RAMAVERSE_PROJECT_STATE.json','client/src/App.tsx','client/src/pages/OwnerCommandCenter.tsx','client/src/lib/ownerCommandCenterData.ts','client/src/pages/OwnerCommandCenter.test.tsx','work_escrow_final/LANGUAGE_REGISTRY.json','work_escrow_final/LANGUAGE_MATRIX.csv','work_escrow_final/V1_5_PHYSICAL_DEVICE_QA_MATRIX.md','release_evidence/global_hardening_20260827/RELEASE_STATE.json','release_evidence/global_hardening_20260827/ROUTE_MATRIX.json','release_evidence/global_hardening_20260827/PWA_VALIDATION.json'].filter(f=>fs.existsSync(path.join(root,f)));
for(const f of files){const src=path.join(out,f);if(!fs.existsSync(src))continue;const dest=path.join(stage,'gap_evidence',f);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.copyFileSync(src,dest);} for(const f of evidence){const dest=path.join(stage,'project_evidence',f);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.copyFileSync(path.join(root,f),dest);}
const notes=`# Master Product Gap Closure\n\nThis archive records a forensic, evidence-first gap recovery pass for the existing RamaVerse Website. It does not deploy, modify Mobile VC14, mutate the canonical 550 baseline, publish staging, or invent missing data/assets.\n\nThe parity percentage is calculated as requirements whose Website and Mobile statuses are both COMPLETE. Mobile statuses are evidence statuses: where the current physically available artifacts do not prove implementation or physical QA, the matrix marks the gap as requiring Mobile work or QA.\n\nOwner Command Center status is PASS. Its source is included as evidence and its route is admin-gated.\n`;
fs.writeFileSync(path.join(stage,'GAP_CLOSURE_README.md'),notes);
const validation={generatedAt:new Date().toISOString(),decision:summary.ownerDashboard==='PASS'?'EVIDENCE_COMPLETE_IMPLEMENTATION_DEFERRED':'BLOCKED',requirements:summary.requirements,complete:summary.classification.COMPLETE,partial:summary.classification.PARTIAL,missing:summary.classification.MISSING_WEBSITE+summary.classification.MISSING_DATA+summary.classification.MISSING_ASSET+summary.classification.MISSING_MOBILE+summary.classification.MISSING_LANGUAGE,websiteGaps:summary.websiteGaps,mobileGaps:summary.mobileGaps,dataGaps:summary.dataGaps,mediaGaps:summary.mediaGaps,languageGaps:summary.languageGaps,implementedThisRun:summary.implementedThisRun,ownerDashboard:summary.ownerDashboard,websiteMobileParityPercent:summary.websiteMobileParityPercent,canonicalChanged:0,stagingPublished:0,mobileModified:false,productionDeployed:false,notes:['Website and Mobile implementations were not rebuilt.','No fabricated content, media, devotional claims, or release evidence was added.']};fs.writeFileSync(path.join(stage,'GAP_CLOSURE_VALIDATION.json'),JSON.stringify(validation,null,2)+'\n');
const sha=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');const names=[];const walk=d=>{for(const n of fs.readdirSync(d)){const p=path.join(d,n);if(fs.statSync(p).isDirectory())walk(p);else names.push(path.relative(stage,p).replaceAll('\\','/'));}};walk(stage);names.sort();fs.writeFileSync(path.join(stage,'SHA256SUMS.txt'),names.map(n=>`${sha(path.join(stage,n))}  ${n}`).join('\n')+'\n');
const zip=path.join(out,'RAMAVERSE-MASTER-PRODUCT-GAP-CLOSURE.zip');fs.rmSync(zip,{force:true});execFileSync('zip',['-q','-X','-r',zip,'.'],{cwd:stage});execFileSync('unzip',['-tq',zip]);const entries=execFileSync('unzip',['-Z1',zip],{encoding:'utf8'}).trim().split('\n').filter(Boolean);const archive={filename:path.basename(zip),integrity:'PASS',entryCount:entries.length,bytes:fs.statSync(zip).size,sha256:sha(zip)};fs.writeFileSync(path.join(out,'ARCHIVE_VERIFICATION.json'),JSON.stringify(archive,null,2)+'\n');fs.writeFileSync(path.join(out,'GAP_CLOSURE_VALIDATION.json'),JSON.stringify(validation,null,2)+'\n');console.log(JSON.stringify({validation,archive},null,2));
