import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';
const root='/home/ubuntu/ramaverse'; const out=path.join(root,'release_evidence','owner_command_center_20260827'); const stage=path.join(out,'package_workspace'); fs.rmSync(stage,{recursive:true,force:true}); fs.mkdirSync(stage,{recursive:true});
const data=fs.readFileSync(path.join(root,'client/src/lib/ownerCommandCenterData.ts'),'utf8'); const page=fs.readFileSync(path.join(root,'client/src/pages/OwnerCommandCenter.tsx'),'utf8');
const sectionIds=['health','corpus','content','languages','media','parity','release','quality','actions'];
const validation={generatedAt:new Date().toISOString(),dashboard:'Owner Command Center',privacy:{route:'owner-command-center',adminGated:page.includes('auth.user.role !== "admin"'),noFakeActions:page.includes('There are no fake buttons here'),publicNavigationLink:false},sections:sectionIds.map(id=>({id,present:page.includes(`id="${id}"`)})),truth:{canonicalBaseline:550,activeCorpus:'v1.4.0',candidateCorpus:1092,stagingPublished:0,duplicateIDs:0,danglingIDs:0,sourceHolds:1,textualVariants:3,tamilHumanReviewed:0,mobileModified:false,productionDeployed:false},evidenceFiles:['RAMAVERSE_PROJECT_STATE.json','release_evidence/global_hardening_20260827/RELEASE_STATE.json','release_evidence/global_hardening_20260827/HEALTH_CONTRACT.json','release_evidence/global_hardening_20260827/CORPUS_VERSION.json','work_escrow_final/RAMAVERSE_COMPLETE_CORPUS_COVERAGE_MATRIX.json','work_escrow_final/LANGUAGE_REGISTRY.json','work_escrow_final/LANGUAGE_MATRIX.csv','work_escrow_final/V1_5_PHYSICAL_DEVICE_QA_MATRIX.md','work_escrow_final/WEBSITE_MOBILE_CORPUS_SYNC_REPORT_V4.md']};
validation.allSectionsPresent=validation.sections.every(x=>x.present); validation.decision=validation.allSectionsPresent&&validation.privacy.adminGated&&validation.privacy.noFakeActions?'PASS':'BLOCKED'; fs.writeFileSync(path.join(out,'OWNER_COMMAND_CENTER_VALIDATION.json'),JSON.stringify(validation,null,2)+'\n');
const qa=`# Owner Command Center visual QA\n\nGenerated ${validation.generatedAt}.\n\nThe route is intentionally admin-gated. In the available preview session the unauthenticated state rendered the restricted-access screen, confirming that the dashboard does not expose operational data anonymously. Authenticated-owner rendering is covered by the route contract and build validation. The implementation uses a dense but responsive evidence layout: health cards, corpus KPIs, semantic tables, missing-asset cards, parity filters, release fields, quality gates, and owner actions. No deployment or mutation control is exposed as a fake UI button.\n\nThe dashboard preserves narrow-screen overflow safety through scrollable tables, stacked cards, and responsive grid breakpoints. Status labels are text-based and remain understandable without color.\n`;
fs.writeFileSync(path.join(out,'OWNER_COMMAND_CENTER_VISUAL_QA.md'),qa);
const files=['client/src/pages/OwnerCommandCenter.tsx','client/src/pages/OwnerCommandCenter.test.tsx','client/src/lib/ownerCommandCenterData.ts','client/src/App.tsx','client/src/index.css','release_evidence/owner_command_center_20260827/OWNER_COMMAND_CENTER_VALIDATION.json','release_evidence/owner_command_center_20260827/OWNER_COMMAND_CENTER_VISUAL_QA.md','RAMAVERSE_PROJECT_STATE.json'].filter(f=>fs.existsSync(path.join(root,f)));
for(const f of files){const dest=path.join(stage,f);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.copyFileSync(path.join(root,f),dest);}
const sha=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'); const list=[]; const walk=d=>{for(const n of fs.readdirSync(d)){const p=path.join(d,n);if(fs.statSync(p).isDirectory())walk(p);else list.push(path.relative(stage,p).replaceAll('\\','/'));}};walk(stage);list.sort();fs.writeFileSync(path.join(stage,'SHA256SUMS.txt'),list.map(n=>`${sha(path.join(stage,n))}  ${n}`).join('\n')+'\n');
const zip=path.join(out,'RAMAVERSE-OWNER-COMMAND-CENTER-RC.zip');fs.rmSync(zip,{force:true});execFileSync('zip',['-q','-X','-r',zip,'.'],{cwd:stage});execFileSync('unzip',['-tq',zip]);const entries=execFileSync('unzip',['-Z1',zip],{encoding:'utf8'}).trim().split('\n').filter(Boolean);const archive={filename:path.basename(zip),integrity:'PASS',entries,entryCount:entries.length,bytes:fs.statSync(zip).size,sha256:sha(zip)};fs.writeFileSync(path.join(out,'ARCHIVE_VERIFICATION.json'),JSON.stringify(archive,null,2)+'\n');console.log(JSON.stringify({validation,archive},null,2)); if(validation.decision!=='PASS')process.exitCode=1;
