import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const root = '/home/ubuntu/ramaverse';
const out = path.join(root, 'release_evidence', 'forgotten_requirements_20260827');
fs.mkdirSync(out, { recursive: true });
const exists = p => fs.existsSync(path.join(root, p));
const read = p => exists(p) ? fs.readFileSync(path.join(root, p), 'utf8') : '';
const pages = fs.readdirSync(path.join(root, 'client/src/pages')).filter(n => n.endsWith('.tsx')).map(n => n.replace('.tsx',''));
const components = fs.readdirSync(path.join(root, 'client/src/components')).filter(n => n.endsWith('.tsx')).map(n => n.replace('.tsx',''));
const app = read('client/src/App.tsx');
const mobileEvidence = ['work_escrow_final/mobile_candidate_pack','work_escrow_final/mobile_candidate_pack_v2','work_escrow_final/mobile_candidate_pack_v3','work_escrow_final/mobile_v1_5_handoff'].filter(exists);
const evidenceFiles = [
  'RAMAVERSE_PROJECT_STATE.json','RAMAVERSE_STAGING_MASTER_LEDGER.json','RECONCILIATION_DRY_RUN.json','client/src/App.tsx','client/src/contexts/MultilingualContext.tsx','client/public/manifest.json','client/public/sw.js','client/public/robots.txt','client/public/sitemap.xml','.gitlab-ci.yml',
  'work_escrow_final/RAMAVERSE_COMPLETENESS_BLUEPRINT_STATE.json','work_escrow_final/RAMAVERSE_COMPLETE_CORPUS_COVERAGE_MATRIX.json','work_escrow_final/RAMAVERSE_COVERAGE_MATRIX.json','work_escrow_final/RAMAVERSE_GAP_MATRIX.csv','work_escrow_final/ROUTE_MATRIX.csv','work_escrow_final/LANGUAGE_MATRIX.csv','work_escrow_final/WEBSITE_MOBILE_CORPUS_SYNC_REPORT_V4.md','work_escrow_final/SOURCE_AUTHORITY_MATRIX.json','work_escrow_final/RAMAVERSE_PRODUCTION_ROUTE_MATRIX.json'
].filter(exists);
const checksum = p => crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex');
const feature = (id, name, category, status, evidence, mobile, data, missing, priority) => ({ id, feature:name, category, classification:status, websiteEvidence:evidence, androidEvidence:mobile, dataAvailability:data, missingWork:missing, priority });
const complete='IMPLEMENTED_COMPLETE', partial='IMPLEMENTED_PARTIAL', webMissing='WEBSITE_MISSING', mobileMissing='MOBILE_MISSING', dataMissing='DATA_MISSING', designMissing='DESIGN_MISSING', assetMissing='ASSET_MISSING', qaMissing='QA_MISSING', notSafe='NOT_SAFE_TO_IMPLEMENT';
const req = [
feature('R-001','Hero imagery','visual',designMissing,['client/src/pages/Home.tsx','client/src/index.css'],'No verified Android visual asset pack is active','Governed text and CSS motifs available','Owner-approved original imagery/art direction is missing; CSS abstract hero is present','P2'),
feature('R-002','Rama character art','visual',assetMissing,['client/src/pages/Characters.tsx'],'Read-only Mobile evidence packs only','Character metadata exists; no approved art asset','Source-cleared original art asset and license record','P2'),
feature('R-003','Sita character art','visual',assetMissing,['client/src/pages/Characters.tsx'],'Read-only Mobile evidence packs only','Character metadata exists; no approved art asset','Source-cleared original art asset and license record','P2'),
feature('R-004','Hanuman character art','visual',assetMissing,['client/src/pages/Characters.tsx'],'Read-only Mobile evidence packs only','Character metadata exists; no approved art asset','Source-cleared original art asset and license record','P2'),
feature('R-005','Lakshmana character art','visual',assetMissing,['client/src/pages/Characters.tsx'],'Read-only Mobile evidence packs only','Character metadata exists; no approved art asset','Source-cleared original art asset and license record','P2'),
feature('R-006','Bharata character art','visual',assetMissing,['client/src/pages/Characters.tsx'],'Read-only Mobile evidence packs only','Character metadata exists; no approved art asset','Source-cleared original art asset and license record','P2'),
feature('R-007','Ravana character art','visual',assetMissing,['client/src/pages/Characters.tsx'],'Read-only Mobile evidence packs only','Character metadata exists; no approved art asset','Source-cleared original art asset and license record','P2'),
feature('R-008','Jatayu / Shabari / Sugriva / Vibhishana art','visual',assetMissing,['client/src/pages/Characters.tsx'],'Read-only Mobile evidence packs only','Character metadata exists; no approved art asset','Source-cleared original art asset and license record','P2'),
feature('R-009','Kanda hero art','visual',designMissing,['client/src/components/KandaAtmosphere.tsx','client/src/index.css'],'No verified Android parity asset','Seven Kanda labels and CSS atmospheres exist','Commission or approve original abstract/illustrative Kanda assets','P2'),
feature('R-010','Cinematic transitions','motion',complete,['client/src/components/motion/MotionPrimitives.tsx','client/src/index.css'],'Mobile evidence mentions reduced-motion-safe transitions','CSS transitions and reduced-motion rule available','None for Website baseline','P2'),
feature('R-011','Rama Setu experience','story',partial,['client/src/pages/Journey.tsx','client/src/pages/Timeline.tsx'],'No verified Mobile feature mapping in active pack','Journey and timeline data exist; dedicated Setu module not separately evidenced','Dedicated source-backed Setu interaction if approved','P2'),
feature('R-012','Journey map','story',complete,['client/src/pages/Journey.tsx','client/src/components/Map.tsx'],'Mobile parity not established','Journey route and map component exist','Mobile parity implementation evidence','P1'),
feature('R-013','Relationship graph','knowledge',partial,['client/src/pages/KnowledgeGraph.tsx','client/src/lib/knowledgeUniverse.ts'],'Mobile parity not established','Approved records and provenance links exist; semantic edges are conservatively zero','Add only source-proven semantic edges; otherwise retain provenance graph','P1'),
feature('R-014','Character universe','knowledge',complete,['client/src/pages/Characters.tsx','server/routers/ramaverse.ts'],'Mobile parity not established','51 governed character pages','Mobile parity implementation evidence','P1'),
feature('R-015','Timeline','knowledge',complete,['client/src/pages/Timeline.tsx'],'Mobile parity not established','Timeline route exists','Mobile parity implementation evidence','P1'),
feature('R-016','Source explorer','knowledge',complete,['client/src/pages/KnowledgeGraph.tsx','client/src/lib/knowledgeUniverse.ts'],'Mobile parity not established','1,092 approved records with source IDs and locators','Mobile parity implementation evidence','P1'),
feature('R-017','Daily Rama wisdom','devotion',partial,['client/src/pages/Wisdom.tsx','client/src/pages/Home.tsx'],'No verified Mobile scheduler evidence','108 wisdom records; daily rotation contract not separately evidenced','Owner-approved deterministic daily selection and notification boundary','P2'),
feature('R-018','Daily nama','devotion',dataMissing,['client/src/pages/Audio.tsx'],'No verified Mobile data contract','No approved daily-nama corpus identified','Source/tradition-approved content and scheduling contract','P3'),
feature('R-019','Ask RamaVerse','intelligence',complete,['client/src/pages/AskRamaVerse.tsx','server/intelligence.ts'],'Read-only Mobile evidence only','Canonical-only deterministic retrieval and evidence display','Mobile parity implementation evidence','P1'),
feature('R-020','Life guidance','learning',complete,['client/src/pages/Guidance.tsx','server/routers/ramaverse.ts'],'No verified Mobile parity evidence','Governed guidance route exists','Mobile parity implementation evidence','P1'),
feature('R-021','Rama Speaks','learning',partial,['client/src/pages/Intelligence.tsx','server/sourceGovernedCanonical.ts'],'No verified Mobile parity evidence','Source-governed dialogue structures exist; direct quotation safeguards apply','Complete editorially approved dialogue coverage','P2'),
feature('R-022','Leadership lessons','learning',partial,['client/src/pages/Wisdom.tsx','client/src/pages/Guidance.tsx'],'No verified Mobile parity evidence','Wisdom/guidance surfaces exist','Explicit source-linked leadership lesson taxonomy','P2'),
feature('R-023','Children mode','learning',complete,['client/src/pages/Stories.tsx','client/src/pages/Quizzes.tsx'],'Read-only Mobile evidence packs mention age-banded lessons','30 stories and 100 quizzes in existing Website data','Mobile parity implementation evidence','P1'),
feature('R-024','Family mode','learning',dataMissing,['client/src/pages/Home.tsx'],'No verified Mobile parity evidence','No separate family-mode contract found','Product definition and governed content mapping','P3'),
feature('R-025','Audio','media',complete,['client/src/pages/Audio.tsx'],'Read-only Mobile evidence only','30 audio scripts and browser-safe playback surface','Mobile parity implementation evidence','P1'),
feature('R-026','Read aloud','media',complete,['client/src/pages/SargaReader.tsx','client/src/pages/Audio.tsx'],'Read-only Mobile evidence only','Web Speech API/read-aloud surface exists','Mobile parity implementation evidence','P1'),
feature('R-027','Chant follow-along','media',designMissing,['client/src/pages/Audio.tsx'],'No verified Mobile contract','No approved synchronized chant dataset identified','Source/tradition-approved timing/audio contract','P3'),
feature('R-028','Lyrics synchronization','media',dataMissing,['client/src/pages/Audio.tsx'],'No verified Mobile contract','No synchronized lyric timing data identified','Approved lyrics/timing dataset','P3'),
feature('R-029','Bookmarks','library',complete,['client/src/contexts/LibraryContext.tsx','client/src/pages/Library.tsx'],'No verified Mobile parity evidence','Local Library provider exists','Mobile parity implementation evidence','P1'),
feature('R-030','Favorites','library',complete,['client/src/contexts/LibraryContext.tsx','client/src/pages/Library.tsx'],'No verified Mobile parity evidence','Local Library provider exists','Mobile parity implementation evidence','P1'),
feature('R-031','Reading history','library',complete,['client/src/contexts/LibraryContext.tsx','client/src/pages/Library.tsx'],'No verified Mobile parity evidence','Local device library state exists','Mobile parity implementation evidence','P1'),
feature('R-032','Continue reading','library',complete,['client/src/pages/Home.tsx','client/src/pages/Library.tsx','client/src/pages/SargaReader.tsx'],'No verified Mobile parity evidence','Reader progress and local library support exist','Mobile parity implementation evidence','P1'),
feature('R-033','Daily notification architecture','operations',webMissing,['server/_core/heartbeat.ts','client/src/pages/Home.tsx'],'No verified Mobile notification contract in active Website task','Heartbeat infrastructure exists but no product notification contract is evidenced','Owner-authorized schedule, privacy, and notification delivery design','P3'),
feature('R-034','Offline packs','pwa',partial,['client/public/sw.js','client/public/manifest.json'],'No verified Mobile offline-pack contract','Offline shell is implemented; governed corpus pack export is not established','Versioned offline pack contract with integrity checks','P2'),
feature('R-035','Install PWA','pwa',complete,['client/public/manifest.json','client/public/sw.js'],'No verified Mobile parity evidence','Manifest, service worker, reset flow','None for Website baseline','P1'),
feature('R-036','Language selector','language',complete,['client/src/components/LanguageSelector.tsx','client/src/contexts/MultilingualContext.tsx'],'Read-only Mobile language metadata packs exist','EN/TA/HI/TE/KN/ML UI routing and persistence exist','Mobile parity implementation evidence','P1'),
feature('R-037','Script selector','language',partial,['client/src/components/LanguageSelector.tsx','client/src/contexts/MultilingualContext.tsx'],'No verified Mobile script-selector contract','Locale selection controls script; separate script-only selection is not evidenced','Define safe script-vs-content selector contract','P2'),
feature('R-038','Transliteration','language',dataMissing,['client/src/contexts/MultilingualContext.tsx'],'No verified Mobile transliteration contract','No approved transliteration field set identified','Source-safe transliteration dataset and review status','P3'),
feature('R-039','Accessibility','quality',complete,['client/src/lib/accessibility.ts','client/src/index.css'],'Read-only Mobile evidence mentions screen-reader and touch targets','Skip link, focus, semantic controls, reduced motion, responsive safeguards','Continue route-level QA','P1'),
feature('R-040','Large text','quality',complete,['client/src/pages/SargaReader.tsx','client/src/index.css'],'No verified Mobile parity evidence','Reader typography controls and script-safe styles exist','Mobile parity implementation evidence','P1'),
feature('R-041','Reduced motion','quality',complete,['client/src/index.css','client/src/components/motion/MotionPrimitives.tsx'],'Read-only Mobile evidence mentions reduced-motion fallback','Global media rule and component safeguards exist','None for Website baseline','P1'),
feature('R-042','Dark/light devotional modes','visual',complete,['client/src/contexts/ThemeContext.tsx','client/src/index.css'],'No verified Mobile parity evidence','Theme provider and devotional dark system exist; light mode is a theme capability','Visual QA for light theme if enabled','P2'),
feature('R-043','Shareable quote cards','social',designMissing,['client/src/pages/Library.tsx','client/src/pages/SargaReader.tsx'],'No verified Mobile contract','No approved quote-card rendering/asset contract identified','Source-safe quote-card design and export flow','P3'),
feature('R-044','Festival mode','devotion',partial,['client/src/pages/Wisdom.tsx','client/src/pages/Guidance.tsx'],'No verified Mobile parity evidence','No dedicated festival route or approved festival calendar found','Tradition-separated calendar and content contract','P3'),
feature('R-045','Temple/pilgrimage','atlas',complete,['client/src/pages/Places.tsx','client/src/pages/Journey.tsx'],'No verified Mobile parity evidence','25 sacred places and Journey route exist','Mobile parity implementation evidence','P1'),
feature('R-046','Global Ramayana traditions','tradition',complete,['client/src/pages/Intelligence.tsx','server/sourceGovernedCanonical.ts'],'No verified Mobile parity evidence','Tradition classification and mapping surfaces exist','Mobile parity implementation evidence','P1'),
feature('R-047','Sources/provenance','governance',complete,['client/src/lib/knowledgeUniverse.ts','server/sourceGovernedCanonical.ts'],'Read-only Mobile pack evidence exists','Source IDs, locators, authority fields, and confidence are present','Mobile parity implementation evidence','P1'),
feature('R-048','Editorial status','governance',complete,['client/src/components/ReviewStatusBadge.tsx','client/src/pages/Kandas.tsx'],'Read-only Mobile evidence exists','Review status and not-published states are visible','Mobile parity implementation evidence','P1'),
feature('R-049','Confidence indicators','governance',complete,['client/src/pages/KnowledgeGraph.tsx','client/src/lib/knowledgeUniverse.ts'],'No verified Mobile parity evidence','Record-level confidence is displayed in the Knowledge Universe','Mobile parity implementation evidence','P1'),
];
const parity = req.map(r => ({ feature:r.feature, website:r.classification===complete||r.classification===partial?'PRESENT':'NOT_COMPLETE', android: r.androidEvidence.some?.(x=>x.includes('Mobile'))?'EVIDENCE_ONLY':'NOT_VERIFIED', dataAvailable:r.dataAvailability, missingWork:r.missingWork, priority:r.priority }));
const counts = Object.fromEntries([...new Set(req.map(r=>r.classification))].map(s=>[s,req.filter(r=>r.classification===s).length]));
const register = { generatedAt:new Date().toISOString(), mode:'RECOVER_COMPARE_IMPLEMENT', scope:'RamaVerse Website with read-only Mobile parity evidence', productionDeployment:'NOT_PERFORMED', canonicalBaseline:550, stagingPublished:0, totalRequirements:req.length, classifications:counts, requirements:req, physicalEvidence:{rootFileCount:fs.readdirSync(root).length,evidenceFiles:evidenceFiles.map(f=>({file:f,sha256:checksum(f)})),websitePages:pages,websiteComponents:components,mobileEvidenceRoots:mobileEvidence,notes:'Mobile source was not modified; no unsupported parity was inferred.'} };
fs.writeFileSync(path.join(out,'RAMAVERSE_MASTER_REQUIREMENT_REGISTER.json'),JSON.stringify(register,null,2)+'\n');
fs.writeFileSync(path.join(out,'WEBSITE_ANDROID_PARITY_MATRIX.json'),JSON.stringify({generatedAt:register.generatedAt,websiteSource:'current /home/ubuntu/ramaverse',androidSource:'read-only evidence only',rows:parity},null,2)+'\n');
const top20=req.filter(r=>r.classification!==complete).sort((a,b)=>a.priority.localeCompare(b.priority)||a.id.localeCompare(b.id)).slice(0,20).map(r=>({id:r.id,feature:r.feature,classification:r.classification,missingWork:r.missingWork,priority:r.priority}));
fs.writeFileSync(path.join(out,'TOP_20_REMAINING.json'),JSON.stringify(top20,null,2)+'\n');
console.log(JSON.stringify({total:req.length,counts,top20,websitePages:pages.length,mobileEvidenceRoots:mobileEvidence.length},null,2));
