import fs from "node:fs";
import path from "node:path";

const root = "/home/ubuntu/ramaverse";
const read = (relative) => JSON.parse(fs.readFileSync(path.join(root, relative), "utf8"));
const write = (relative, value) => fs.writeFileSync(path.join(root, relative), JSON.stringify(value, null, 2) + "\n");
const names = fs.readdirSync(path.join(root, "data/staging/post_v1")).filter((name) => /^AYODHYA_S\d+_SOURCE_BACKED_RECORDS\.json$/.test(name)).sort((a, b) => Number(a.match(/S(\d+)/)[1]) - Number(b.match(/S(\d+)/)[1]));
const payloads = [{ path: "data/staging/physical/STAGING_RECORDS.json", records: read("data/staging/physical/STAGING_RECORDS.json") }, ...names.map((name) => ({ path: `data/staging/post_v1/${name}`, batch: read(`data/staging/post_v1/${name}`) }))];
for (const payload of payloads.slice(1)) payload.records = payload.batch.records ?? [];
const records = payloads.flatMap((payload) => payload.records.map((record) => ({ ...record, _payload: payload.path })));
const ledger = read("RAMAVERSE_STAGING_MASTER_LEDGER_V3.json"), sources = read("SOURCE_LEDGER_V3.json"), continuation = read("EXACT_PHYSICAL_CONTINUATION_V3.json"), queue = read("TAMIL_EDITORIAL_REVIEW_QUEUE_V3.json"), variants = read("TEXTUAL_VARIANCE_LEDGER_V2.json");
const sourceIds = new Set(sources.sources.map((source) => source.source_id)), seen = new Set(), duplicateIds = [], missingFields = [], missingSourceIds = [];
const required = [["candidate_id", (record) => Boolean(record.candidate_id)], ["record_type", (record) => Boolean(record.record_type)], ["kanda", (record) => Boolean(record.kanda)], ["sarga", (record) => Boolean(record.sarga ?? record.verse_locator)], ["verse_locator", (record) => Boolean(record.verse_locator ?? record.locator)], ["source_id", (record) => Boolean(record.source_id) || (Array.isArray(record.source) && record.source.length)], ["source_locator", (record) => Boolean(record.source_locator ?? record.canonical_source_locator ?? record.locator)], ["source_type", (record) => Boolean(record.source_type)], ["tradition_classification", (record) => Boolean(record.tradition_classification)], ["english_explanation", (record) => Boolean(record.english_explanation ?? record.summary)], ["tamil_review_status", (record) => Boolean(record.tamil_review_status ?? record.review_status)], ["merge_state", (record) => Boolean(record.merge_state)], ["possible_legacy_overlap", (record) => typeof record.possible_legacy_overlap === "boolean"], ["publication_policy", (record) => record.publication_policy === "STAGING_QUARANTINE_ONLY"]];
for (const record of records) { if (seen.has(record.candidate_id)) duplicateIds.push(record.candidate_id); seen.add(record.candidate_id); for (const [field, check] of required) if (!check(record)) missingFields.push({ id: record.candidate_id, field }); for (const sourceId of [...new Set([record.source_id, ...(record.source ?? [])].filter(Boolean))]) if (!sourceIds.has(sourceId) && sourceId !== "src-gretil-ramayana-kandas-1-7") missingSourceIds.push({ id: record.candidate_id, source_id: sourceId }); }
const payloadCounts = payloads.map((payload) => ({ path: payload.path, actual: payload.records.length, declared: payload.batch?.recordCount ?? payload.records.length, match: !payload.batch || payload.records.length === payload.batch.recordCount })), sargaCounts = Object.fromEntries([...new Set(records.map((record) => record.sarga).filter(Boolean))].sort((a, b) => Number(a) - Number(b)).map((sarga) => [sarga, records.filter((record) => Number(record.sarga) === Number(sarga)).length]));
const audit = { auditId: "ramaverse-post-v1-staging-physical-audit-v3", generatedAt: new Date().toISOString(), physicalRecordCount: records.length, ledgerRecordCount: ledger.physicallyAvailableUniqueRecords, physicalLedgerMatch: records.length === ledger.physicallyAvailableUniqueRecords, uniqueIds: new Set(records.map((record) => record.candidate_id)).size, duplicateStableIds: duplicateIds, missingSourceIds, missingRequiredFields: missingFields, payloadCounts, sargaCoverage: sargaCounts, valid: records.length === ledger.physicallyAvailableUniqueRecords && duplicateIds.length === 0 && missingFields.length === 0 && missingSourceIds.length === 0 && payloadCounts.every((payload) => payload.match) };
write("POST_V1_STAGING_PHYSICAL_AUDIT_V3.json", audit);
const allowedStates = new Set(["MACHINE_DRAFT_NEEDS_REVIEW", "EDITORIAL_DRAFT_READY_FOR_HUMAN_REVIEW", "SOURCE_TRANSLATION_AVAILABLE", "TRANSLITERATION_ONLY", "NOT_AVAILABLE"]), queueStateErrors = queue.records.filter((record) => !allowedStates.has(record.translation_status)).map((record) => ({ id: record.record_id, state: record.translation_status })), noFalseHumanReview = queue.humanReviewedCount === 0 && queue.records.every((record) => record.human_reviewed === false);
const validation = { validationId: "ramaverse-post-v1-staging-validation-v3", generatedAt: new Date().toISOString(), physicalRecordCount: records.length, ledgerStagingCount: ledger.physicallyAvailableUniqueRecords, physicalLedgerMatch: audit.physicalLedgerMatch, uniqueIds: audit.uniqueIds, duplicateIds, missingFields, missingSourceIds, sourceCount: sources.sources.length, payloadCounts, stagingPublished: ledger.stagingPublished, publicSearchStaging: ledger.publicSurfacePolicy.stagingExposure, publicAskStaging: ledger.publicSurfacePolicy.stagingExposure, publicGraphStaging: 0, frozenMobilePackModified: false, tamilReviewQueue: queue.records.length, tamilQueueStateErrors: queueStateErrors, humanReviewedCount: queue.humanReviewedCount, noFalseHumanReview, editorialDraftsImproved: queue.editorialDraftsImprovedThisRun, textualVariants: variants.count, exactContinuation: continuation.next_unacquired_verse, valid: false };
validation.valid = audit.valid && validation.stagingPublished === 0 && validation.publicSearchStaging === 0 && validation.publicAskStaging === 0 && validation.publicGraphStaging === 0 && !validation.frozenMobilePackModified && validation.tamilReviewQueue === records.length && queueStateErrors.length === 0 && noFalseHumanReview && validation.editorialDraftsImproved >= 36 && validation.textualVariants === 2 && validation.exactContinuation === "2.36.1";
write("POST_V1_STAGING_VALIDATION_V3.json", validation);
const postRun = { stateId: "ramaverse-post-run-authority-state-v3", generatedAt: new Date().toISOString(), canonicalProduction: 550, physicalStaging: records.length, ledgerStaging: ledger.physicallyAvailableUniqueRecords, physicalLedgerMatch: validation.physicalLedgerMatch, uniqueIds: audit.uniqueIds, duplicateIds, missingSourceIds, sourceCount: sources.sources.length, tamilReviewQueue: queue.records.length, tamilReviewStates: queue.countsByTranslationState, editorialDraftsImproved: queue.editorialDraftsImprovedThisRun, humanReviewedCount: queue.humanReviewedCount, textualVariants: variants.count, sargaCoverage: sargaCounts, latestFullyAcquired: { kanda: continuation.last_fully_acquired_kanda, sarga: continuation.last_fully_acquired_sarga, verse: continuation.last_fully_acquired_verse }, nextUnacquiredVerse: continuation.next_unacquired_verse, stagingPublished: ledger.stagingPublished, publicSearchStaging: ledger.publicSurfacePolicy.stagingExposure, publicAskStaging: ledger.publicSurfacePolicy.stagingExposure, frozenMobilePackModified: false, validationPass: validation.valid, status: validation.valid ? "PASS" : "NO_GO" };
write("POST_RUN_AUTHORITY_STATE_V3.json", postRun);
console.log(JSON.stringify({ validation, postRun }, null, 2)); if (!validation.valid) process.exit(1);
